CREATE TABLE [dbo].[EV_SF_QUOTE] (
    [ID]                                      NVARCHAR (18)    NULL,
    [ISDELETED]                               INT              NULL,
    [NAME]                                    NVARCHAR (255)   NULL,
    [CURRENCYISOCODE]                         NVARCHAR (3)     NULL,
    [RECORDTYPEID]                            NVARCHAR (18)    NULL,
    [CREATEDDATE]                             DATETIME         NULL,
    [CREATEDBYID]                             NVARCHAR (18)    NULL,
    [LASTMODIFIEDDATE]                        DATETIME         NULL,
    [LASTMODIFIEDBYID]                        NVARCHAR (18)    NULL,
    [SYSTEMMODSTAMP]                          DATETIME         NULL,
    [LASTVIEWEDDATE]                          DATETIME         NULL,
    [LASTREFERENCEDDATE]                      DATETIME         NULL,
    [OPPORTUNITYID]                           NVARCHAR (18)    NULL,
    [PRICEBOOK2ID]                            NVARCHAR (18)    NULL,
    [CONTACTID]                               NVARCHAR (18)    NULL,
    [QUOTENUMBER]                             NVARCHAR (30)    NULL,
    [ISSYNCING]                               INT              NULL,
    [SHIPPINGHANDLING]                        DECIMAL (18, 2)  NULL,
    [TAX]                                     DECIMAL (18, 2)  NULL,
    [STATUS]                                  NVARCHAR (40)    NULL,
    [EXPIRATIONDATE]                          DATETIME         NULL,
    [DESCRIPTION]                             NTEXT            NULL,
    [SUBTOTAL]                                DECIMAL (18, 2)  NULL,
    [TOTALPRICE]                              DECIMAL (18, 2)  NULL,
    [LINEITEMCOUNT]                           INT              NULL,
    [BILLINGSTREET]                           NVARCHAR (255)   NULL,
    [BILLINGCITY]                             NVARCHAR (40)    NULL,
    [BILLINGSTATE]                            NVARCHAR (80)    NULL,
    [BILLINGPOSTALCODE]                       NVARCHAR (20)    NULL,
    [BILLINGCOUNTRY]                          NVARCHAR (80)    NULL,
    [BILLINGLATITUDE]                         DECIMAL (18, 15) NULL,
    [BILLINGLONGITUDE]                        DECIMAL (18, 15) NULL,
    [SHIPPINGSTREET]                          NVARCHAR (255)   NULL,
    [SHIPPINGCITY]                            NVARCHAR (40)    NULL,
    [SHIPPINGSTATE]                           NVARCHAR (80)    NULL,
    [SHIPPINGPOSTALCODE]                      NVARCHAR (20)    NULL,
    [SHIPPINGCOUNTRY]                         NVARCHAR (80)    NULL,
    [SHIPPINGLATITUDE]                        DECIMAL (18, 15) NULL,
    [SHIPPINGLONGITUDE]                       DECIMAL (18, 15) NULL,
    [QUOTETOSTREET]                           NVARCHAR (255)   NULL,
    [QUOTETOCITY]                             NVARCHAR (40)    NULL,
    [QUOTETOSTATE]                            NVARCHAR (80)    NULL,
    [QUOTETOPOSTALCODE]                       NVARCHAR (20)    NULL,
    [QUOTETOCOUNTRY]                          NVARCHAR (80)    NULL,
    [QUOTETOLATITUDE]                         DECIMAL (18, 15) NULL,
    [QUOTETOLONGITUDE]                        DECIMAL (18, 15) NULL,
    [ADDITIONALSTREET]                        NVARCHAR (255)   NULL,
    [ADDITIONALCITY]                          NVARCHAR (40)    NULL,
    [ADDITIONALSTATE]                         NVARCHAR (80)    NULL,
    [ADDITIONALPOSTALCODE]                    NVARCHAR (20)    NULL,
    [ADDITIONALCOUNTRY]                       NVARCHAR (80)    NULL,
    [ADDITIONALLATITUDE]                      DECIMAL (18, 15) NULL,
    [ADDITIONALLONGITUDE]                     DECIMAL (18, 15) NULL,
    [BILLINGNAME]                             NVARCHAR (255)   NULL,
    [SHIPPINGNAME]                            NVARCHAR (255)   NULL,
    [QUOTETONAME]                             NVARCHAR (255)   NULL,
    [ADDITIONALNAME]                          NVARCHAR (255)   NULL,
    [EMAIL]                                   NVARCHAR (80)    NULL,
    [PHONE]                                   NVARCHAR (40)    NULL,
    [FAX]                                     NVARCHAR (40)    NULL,
    [ACCOUNTID]                               NVARCHAR (18)    NULL,
    [DISCOUNT]                                DECIMAL (5, 2)   NULL,
    [GRANDTOTAL]                              DECIMAL (18, 2)  NULL,
    [AP_CONTACT_EMAIL__C]                     NVARCHAR (100)   NULL,
    [AP_CONTACT_NAME__C]                      NVARCHAR (100)   NULL,
    [ADDITIONAL_SHIPPING_ADDRESSES__C]        NVARCHAR (500)   NULL,
    [APPROVALS_REQUIRED__C]                   NVARCHAR (1300)  NULL,
    [APPROVED_PAYMENT_TERMS__C]               NVARCHAR (50)    NULL,
    [QUOTE_APPROVED_FLAG__C]                  INT              NULL,
    [APPROVED_RECONTRACT_TERMS__C]            NTEXT            NULL,
    [RECONTRACT_TERMS__C]                     NTEXT            NULL,
    [TERMS__C]                                NTEXT            NULL,
    [QUOTE_APPROVAL_LEVEL__C]                 DECIMAL (2)      NULL,
    [APPROVED_TERMS__C]                       NTEXT            NULL,
    [BILLING_ADDRESS__C]                      NVARCHAR (1300)  NULL,
    [BILLING_CONTACT_EMAIL__C]                NVARCHAR (1300)  NULL,
    [BINDING_PDF_CREATED__C]                  INT              NULL,
    [QA_REQUEST_FROM_RW__C]                   INT              NULL,
    [CFO_APPROVED__C]                         INT              NULL,
    [CONTACT_FIRST_NAME__C]                   NVARCHAR (1300)  NULL,
    [CONTACT_LAST_NAME__C]                    NVARCHAR (1300)  NULL,
    [CONTRACT__C]                             NVARCHAR (18)    NULL,
    [CONTRACTS_APPROVED__C]                   INT              NULL,
    [CONTROLLER_APPROVED__C]                  INT              NULL,
    [CREATED_BY_NAME__C]                      NVARCHAR (1300)  NULL,
    [CUSTOMER_APPROVED__C]                    INT              NULL,
    [CUSTOMER_TYPE__C]                        NVARCHAR (1300)  NULL,
    [DOA_APPROVAL_EXCEEDED__C]                INT              NULL,
    [DEAL_DESK_DISCOUNT_APPROVED__C]          INT              NULL,
    [DEAL_DESK_EXPIRATION_DATE_APPROVED__C]   INT              NULL,
    [DEAL_DESK_INSTRUCTIONS_APPROVED__C]      INT              NULL,
    [DEAL_ID__C]                              NVARCHAR (1300)  NULL,
    [DEAL_TYPE__C]                            NVARCHAR (1300)  NULL,
    [DISCOUNT_APPROVAL_REQUIRED__C]           INT              NULL,
    [DISTRIBUTOR_CONTACT_EMAIL__C]            NVARCHAR (1300)  NULL,
    [DISTRIBUTOR_CONTACT__C]                  NVARCHAR (18)    NULL,
    [DISTRIBUTOR_PO__C]                       NVARCHAR (40)    NULL,
    [DISTRIBUTOR__C]                          NVARCHAR (18)    NULL,
    [EARLY_TERM_FEE__C]                       DECIMAL (18, 2)  NULL,
    [EARLY_TERM_FEES_APPLY__C]                INT              NULL,
    [END_USER_CONTACT__C]                     NVARCHAR (18)    NULL,
    [END_USER_PO__C]                          NVARCHAR (40)    NULL,
    [ESCALATION_REASON_CODE__C]               NVARCHAR (255)   NULL,
    [ESCALATION_REASON_DESCRIPTION__C]        NVARCHAR (255)   NULL,
    [EXPIRATION_DATE_NOT_STANDARD__C]         INT              NULL,
    [FINANCE_ACCT_CREDIT_STATUS_APPROVED__C]  INT              NULL,
    [FINANCE_APPROVED__C]                     INT              NULL,
    [FINANCE_INSTRUCTIONS_APPROVED__C]        INT              NULL,
    [FINANCE_PAYMENT_TERMS_APPROVED__C]       INT              NULL,
    [FINANCE_TERMS_APPROVED__C]               INT              NULL,
    [HAS_CANCELATION_LINES__C]                INT              NULL,
    [HARDWARE_WITH_SERIAL_NUMBER_REQUIRED__C] INT              NULL,
    [INSTALL_RESPONSIBILITY__C]               NVARCHAR (255)   NULL,
    [INTEGRATION_ERROR__C]                    NVARCHAR (255)   NULL,
    [LATEST_DOCUSIGN_ENVELOP_STATUS__C]       NVARCHAR (50)    NULL,
    [LEGAL_APPROVED__C]                       INT              NULL,
    [LEGAL_T_CS_APPROVED__C]                  INT              NULL,
    [NS_QUOTE_ID__C]                          NVARCHAR (10)    NULL,
    [NEEDS_APPROVAL__C]                       INT              NULL,
    [NETSUITE_ORDER_ID__C]                    NVARCHAR (10)    NULL,
    [OPPORTUNITY_TYPE__C]                     NVARCHAR (1300)  NULL,
    [ORDER_APPROVAL_DATE_APPROVED__C]         DATETIME         NULL,
    [ORDER_APPROVAL_DATE_REJECTED__C]         DATETIME         NULL,
    [ORDER_APPROVAL_DATE_SUBMITTED__C]        DATETIME         NULL,
    [ORIGINAL_BILLING_START_DATE__C]          DATETIME         NULL,
    [ORIGINAL_RECONTRACT_TERMS__C]            NTEXT            NULL,
    [PO_NUMBER__C]                            NVARCHAR (50)    NULL,
    [PO_NUMBER_FROM_DOCUSIGN__C]              NVARCHAR (50)    NULL,
    [PARTNER_NAME__C]                         NVARCHAR (18)    NULL,
    [PAYMENT_METHOD__C]                       NVARCHAR (255)   NULL,
    [PAYMENT_TERMS_APPROVED__C]               INT              NULL,
    [PAYMENT_TERMS_CHANGED__C]                INT              NULL,
    [PAYMENT_TERMS__C]                        NVARCHAR (255)   NULL,
    [PROCUREMENT_APPROVED__C]                 INT              NULL,
    [PRODUCT_MANAGEMENT_APPROVED__C]          INT              NULL,
    [PRODUCT_REQUIRES_SERIAL_NUMBER__C]       INT              NULL,
    [QUOTE_APPROVAL_DATE_APPROVED__C]         DATETIME         NULL,
    [QUOTE_APPROVAL_DATE_REJECTED__C]         DATETIME         NULL,
    [QUOTE_APPROVAL_DATE_SUBMITTED__C]        DATETIME         NULL,
    [QUOTE_APPROVED_VIA_DOCUSIGN__C]          INT              NULL,
    [QUOTE_SALES_REP__C]                      NVARCHAR (1300)  NULL,
    [QUOTE_SIGNED_DATE__C]                    DATETIME         NULL,
    [QUOTE_SIGNER_EMAIL__C]                   NVARCHAR (100)   NULL,
    [QUOTE_SIGNER_TITLE__C]                   NVARCHAR (100)   NULL,
    [QUOTE_SIGNER__C]                         NVARCHAR (100)   NULL,
    [RE_CONTRACT_APPROVAL_REQUIRED__C]        INT              NULL,
    [REFERRAL_PARTNER_NAME__C]                NVARCHAR (18)    NULL,
    [RELAYWARE_ID__C]                         DECIMAL (18)     NULL,
    [RENEWAL_QUOTE_LOCK__C]                   INT              NULL,
    [RENEWAL_TYPE__C]                         NVARCHAR (255)   NULL,
    [REQUEST_TYPE__C]                         NVARCHAR (255)   NULL,
    [RESELLER_ACCOUNT__C]                     NVARCHAR (18)    NULL,
    [RESELLER_CITY__C]                        NVARCHAR (100)   NULL,
    [RESELLER_CONTACT_EMAIL__C]               NVARCHAR (1300)  NULL,
    [RESELLER_CONTACT__C]                     NVARCHAR (18)    NULL,
    [RESELLER_COUNTRY__C]                     NVARCHAR (100)   NULL,
    [RESELLER_PO__C]                          NVARCHAR (40)    NULL,
    [RESELLER_STATE__C]                       NVARCHAR (100)   NULL,
    [RESELLER_STREET__C]                      NVARCHAR (100)   NULL,
    [RESELLER_ZIP__C]                         NVARCHAR (30)    NULL,
    [SALES_APPROVER__C]                       NVARCHAR (18)    NULL,
    [SALES_MANAGEMENT_APPROVED__C]            INT              NULL,
    [SALES_MANAGEMENT_DISCOUNT_APPROVED__C]   INT              NULL,
    [SALES_ORDER__C]                          NVARCHAR (18)    NULL,
    [SALES_REP_EMAIL__C]                      NVARCHAR (1300)  NULL,
    [SHIP_TO_COMPANY__C]                      NVARCHAR (255)   NULL,
    [SOLD_TO__C]                              NVARCHAR (18)    NULL,
    [SPECIAL_INSTRUCTIONS_ENTERED__C]         INT              NULL,
    [T_C_S_ADDENDUM__C]                       NTEXT            NULL,
    [T_CS_CHANGED__C]                         INT              NULL,
    [TERM_APPROVAL_REQUIRED2__C]              INT              NULL,
    [TERM_CHANGED_ON_LINE_ITEM__C]            INT              NULL,
    [TIERED_PRICE_QTY__C]                     DECIMAL (18)     NULL,
    [WITHIN_RENEWAL_PERIOD__C]                INT              NULL,
    [MRR__C]                                  DECIMAL (11, 2)  NULL,
    [TAV__C]                                  DECIMAL (18, 2)  NULL,
    [TCV__C]                                  DECIMAL (18, 2)  NULL,
    [TOTAL_MONTHLY_RECURRING_FEES__C]         DECIMAL (18, 4)  NULL,
    [TOTAL_NON_RECURRING_FEES__C]             DECIMAL (18, 4)  NULL,
    [NON_MRR__C]                              DECIMAL (11, 2)  NULL,
    [S_M_RENEWAL_QUOTE_CREATED__C]            INT              NULL,
    [CREATED_BY_PROFILE_NAME__C]              NVARCHAR (1300)  NULL,
    [BILLING_CONTACT__C]                      NVARCHAR (1300)  NULL,
    [BILLING_INSTRUCTIONS__C]                 NVARCHAR (255)   NULL,
    [CANCELATION_DATE__C]                     DATETIME         NULL,
    [CANCELATION_OUTCOME__C]                  NVARCHAR (255)   NULL,
    [CANCELATION_REASON__C]                   NVARCHAR (255)   NULL,
    [CANCELATION_TYPE__C]                     NVARCHAR (255)   NULL,
    [ASSIGNED_SALES_OPS_REP__C]               NVARCHAR (18)    NULL,
    [ORDER_SUBMITTED_BY__C]                   NVARCHAR (255)   NULL,
    [DATA_EXPORT_REQUIRED__C]                 NVARCHAR (255)   NULL,
    [SHOW_DISCOUNT__C]                        INT              NULL,
    [HIDDEN_ADMIN_TEXT_FIELD__C]              NVARCHAR (255)   NULL,
    [ACCOUNT_ID__C]                           NVARCHAR (1300)  NULL,
    [NO_CO_TERM__C]                           INT              NULL,
    [APPROVAL_SUBMITTED_BY__C]                NVARCHAR (255)   NULL,
    [LAST_VOID_TIME__C]                       DATETIME         NULL,
    [LAST_VOID_BY__C]                         NVARCHAR (255)   NULL,
    [LAST_QUOTE_APPROVED_TIME__C]             DATETIME         NULL,
    [LAST_QUOTE_APPROVED_BY__C]               NVARCHAR (255)   NULL,
    [LAST_ORDER_SUBMITTED_TIME__C]            DATETIME         NULL,
    [LAST_ORDER_SUBMITTED_BY__C]              NVARCHAR (255)   NULL,
    [LAST_ORDER_APPROVED_TIME__C]             DATETIME         NULL,
    [LAST_ORDER_APPROVED_BY__C]               NVARCHAR (255)   NULL,
    [LAST_DRAFT_TIME__C]                      DATETIME         NULL,
    [LAST_DRAFT_BY__C]                        NVARCHAR (255)   NULL,
    [PROVISIONING_INSTRUCTIONS__C]            NVARCHAR (1000)  NULL,
    [ORIGINAL_NS_ORDER_NUMBER__C]             NVARCHAR (20)    NULL,
    [ORIGINAL_NS_ORDER_INTERNAL_ID__C]        NVARCHAR (10)    NULL,
    [ORIGINAL_NS_ORDER_DATE__C]               DATETIME         NULL,
    [BILL_TO_CHANGE_APPROVED__C]              INT              NULL,
    [DAS_SUPPORT_ORDER__C]                    INT              NULL,
    [S_M_DISCOUNT_APPROVAL_REQUIRED__C]       INT              NULL,
    [ORIGINATING_DAS_TICKET__C]               NVARCHAR (18)    NULL,
    [REFERRAL_COMMISSION_PERCENT__C]          DECIMAL (3)      NULL,
    [NETSUITE_QUOTE__C]                       INT              NULL,
    [SHOW_LINE_PRICING__C]                    INT              NULL,
    [PROMOTION__C]                            NVARCHAR (80)    NULL,
    [BILL_TO_PAYMENT_TERMS__C]                NVARCHAR (20)    NULL,
    [DATA_CENTER_LOCATION__C]                 NVARCHAR (255)   NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191555968EV_SF_QUOTE_ID]
    ON [dbo].[EV_SF_QUOTE]([ID] ASC);

