CREATE TABLE [dbo].[EV_SF_DATEDCONVERSIONRATE] (
    [ISOCODE]        NVARCHAR (40)   NULL,
    [STARTDATE]      DATETIME2 (7)   NULL,
    [NEXTSTARTDATE]  DATETIME        NULL,
    [CONVERSIONRATE] DECIMAL (18, 6) NULL,
    [CREATEDDATE]    DATETIME        NULL
);

