CREATE TABLE [dbo].[EV_SF_CONTRACT_LINE_ITEM__C] (
    [ID]                               NVARCHAR (18)   NULL,
    [ISDELETED]                        INT             NULL,
    [NAME]                             NVARCHAR (80)   NULL,
    [CURRENCYISOCODE]                  NVARCHAR (3)    NULL,
    [CREATEDDATE]                      DATETIME        NULL,
    [CREATEDBYID]                      NVARCHAR (18)   NULL,
    [LASTMODIFIEDDATE]                 DATETIME        NULL,
    [LASTMODIFIEDBYID]                 NVARCHAR (18)   NULL,
    [SYSTEMMODSTAMP]                   DATETIME        NULL,
    [LASTACTIVITYDATE]                 DATETIME        NULL,
    [LASTVIEWEDDATE]                   DATETIME        NULL,
    [LASTREFERENCEDDATE]               DATETIME        NULL,
    [CONNECTIONRECEIVEDID]             NVARCHAR (18)   NULL,
    [CONNECTIONSENTID]                 NVARCHAR (18)   NULL,
    [CONTRACT__C]                      NVARCHAR (18)   NULL,
    [ACTUAL_USAGE__C]                  INT             NULL,
    [AMOUNT__C]                        DECIMAL (11, 2) NULL,
    [BILL_TO_CUSTOMER__C]              NVARCHAR (18)   NULL,
    [BILLING_ID__C]                    NVARCHAR (255)  NULL,
    [CANCELLATION_DATE__C]             DATETIME        NULL,
    [CHARGE_TYPE__C]                   NVARCHAR (1300) NULL,
    [CONTRACT_BILLING_FREQUENCY__C]    NVARCHAR (255)  NULL,
    [CONTRACT_ID__C]                   NVARCHAR (20)   NULL,
    [CONTRACT_ITEM_TYPE__C]            NVARCHAR (255)  NULL,
    [CONTRACT_LINE_ITEM__C]            NVARCHAR (80)   NULL,
    [CONTRACT_NAME__C]                 NVARCHAR (1300) NULL,
    [CONTRACT_STATUS__C]               NVARCHAR (255)  NULL,
    [CONTRACTED_DISCOUNT_PERCENT__C]   DECIMAL (11, 8) NULL,
    [DAYS_REMAINING__C]                DECIMAL (18)    NULL,
    [DISCOUNT_PERCENT__C]              DECIMAL (11, 8) NULL,
    [DISTRIBUTOR_CONTACT__C]           NVARCHAR (18)   NULL,
    [END_DATE__C]                      DATETIME        NULL,
    [END_USER_CUSTOMER__C]             NVARCHAR (18)   NULL,
    [ITEM_DESCRIPTION__C]              NVARCHAR (275)  NULL,
    [ITEM_NAME__C]                     NVARCHAR (18)   NULL,
    [LICENSE_KEY__C]                   NVARCHAR (255)  NULL,
    [LINE_ITEM_TAV__C]                 DECIMAL (18, 2) NULL,
    [LINE_ITEM_TCV__C]                 DECIMAL (18, 2) NULL,
    [LIST_OVERAGE_RATE__C]             DECIMAL (18, 4) NULL,
    [LIST_PRICE__C]                    DECIMAL (13, 4) NULL,
    [MAINTENANCE_AMOUNT__C]            DECIMAL (11, 2) NULL,
    [NS_CONTRACT_LINE_ID__C]           NVARCHAR (20)   NULL,
    [NS_ORDER_LINE_TXN_ID__C]          NVARCHAR (25)   NULL,
    [NET_OVERAGE_RATE__C]              DECIMAL (18, 4) NULL,
    [ORDER_LINE_TRANSACTION_TYPE__C]   NVARCHAR (255)  NULL,
    [ORDER_TYPE__C]                    NVARCHAR (255)  NULL,
    [OVERAGE_FEES_APPLY__C]            INT             NULL,
    [PO__C]                            NVARCHAR (40)   NULL,
    [PER_GB_RATE__C]                   DECIMAL (6, 2)  NULL,
    [PRICING_GROUP__C]                 NVARCHAR (1300) NULL,
    [PRODUCT_CODE_SKU__C]              NVARCHAR (40)   NULL,
    [PRODUCT_TYPE__C]                  NVARCHAR (80)   NULL,
    [QUANTITY__C]                      DECIMAL (10, 1) NULL,
    [RELATED_SW_APPL_PURCH_PRICE__C]   DECIMAL (18, 2) NULL,
    [RELATED_SW_APPLIANCE_DESC__C]     NVARCHAR (255)  NULL,
    [RELATED_SW_APPLIANCE_ITEM_SKU__C] NVARCHAR (50)   NULL,
    [RELATED_SW_APPLIANCE_ITEM__C]     NVARCHAR (18)   NULL,
    [RENEW_DATE__C]                    DATETIME        NULL,
    [REPORTING_CATEGORY__C]            NVARCHAR (1300) NULL,
    [RESELLER_CONTACT__C]              NVARCHAR (18)   NULL,
    [RESELLER_PARTNER__C]              NVARCHAR (18)   NULL,
    [SALES_ORDER__C]                   NVARCHAR (40)   NULL,
    [SALES_PRICE__C]                   DECIMAL (13, 4) NULL,
    [SERIAL_NUMBER__C]                 NVARCHAR (255)  NULL,
    [SERVER_QUANTITY__C]               DECIMAL (4)     NULL,
    [SHIP_DATE__C]                     DATETIME        NULL,
    [SOURCE_TRANSACTION__C]            NVARCHAR (18)   NULL,
    [STANDARD_INCLUDED_USAGE__C]       DECIMAL (11, 2) NULL,
    [START_DATE__C]                    DATETIME        NULL,
    [SUPPORT_AND_MAINTENANCE_ITEM__C]  NVARCHAR (18)   NULL,
    [TERM__C]                          DECIMAL (2)     NULL,
    [TOTAL_INCLUDED_STORAGE_GB__C]     DECIMAL (18)    NULL,
    [TXM_LINE_UNIQUE_ID__C]            NVARCHAR (40)   NULL,
    [USAGE_UNIT__C]                    NVARCHAR (1300) NULL,
    [WARRANTY_END_DATE__C]             DATETIME        NULL,
    [WARRANTY_ITEM__C]                 NVARCHAR (18)   NULL,
    [WARRANTY_START_DATE__C]           DATETIME        NULL,
    [BILL_TO_CUSTOMER_TYPE__C]         NVARCHAR (1300) NULL,
    [HIDDEN_ADMIN_TEXT_FIELD__C]       NVARCHAR (255)  NULL,
    [RELAYWARE_ID__C]                  DECIMAL (18)    NULL,
    [MONTHLY_RATE_FOR_S_M_LINES__C]    DECIMAL (18, 2) NULL,
    [END_OF_TERM_ACTION__C]            NVARCHAR (20)   NULL,
    [LAST_BILLED_DATE__C]              DATETIME        NULL,
    [NEXT_BILL_DATE__C]                DATETIME        NULL,
    [PROMOTION_DISC__C]                DECIMAL (18, 2) NULL,
    [PROMOTION_FLAG__C]                INT             NULL,
    [SUPERSEDED_BY__C]                 NVARCHAR (18)   NULL,
    [SUPERSEDES__C]                    NVARCHAR (18)   NULL,
    [ORIGINAL_NS_CONTRACT_LINE_ID__C]  NVARCHAR (20)   NULL,
    [CARBONITE_CONTRACT_LINE__C]       INT             NULL,
    [SEAGATE_CONTRACT_LINE__C]         INT             NULL,
    [NEW_CARBONITE_NETSUITE_ID__C]     NVARCHAR (8)    NULL,
    [LINE_ID__C]                       NVARCHAR (3)    NULL,
    [ORIGINAL_TERM__C]                 NVARCHAR (6)    NULL,
    [PARENT_LINE_ID__C]                NVARCHAR (3)    NULL,
    [STORAGE_TYPE__C]                  NVARCHAR (30)   NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191533498EV_SF_CONTRACT_L]
    ON [dbo].[EV_SF_CONTRACT_LINE_ITEM__C]([ID] ASC);

