CREATE TABLE [dbo].[EV_SF_OPPORTUNITYLINEITEM] (
    [ID]                                     NVARCHAR (18)   NULL,
    [OPPORTUNITYID]                          NVARCHAR (18)   NULL,
    [SORTORDER]                              INT             NULL,
    [PRICEBOOKENTRYID]                       NVARCHAR (18)   NULL,
    [PRODUCT2ID]                             NVARCHAR (18)   NULL,
    [PRODUCTCODE]                            NVARCHAR (255)  NULL,
    [NAME]                                   NVARCHAR (376)  NULL,
    [CURRENCYISOCODE]                        NVARCHAR (3)    NULL,
    [QUANTITY]                               DECIMAL (12, 2) NULL,
    [DISCOUNT]                               DECIMAL (5, 2)  NULL,
    [TOTALPRICE]                             DECIMAL (18, 2) NULL,
    [UNITPRICE]                              DECIMAL (18, 2) NULL,
    [LISTPRICE]                              DECIMAL (18, 2) NULL,
    [SERVICEDATE]                            DATETIME        NULL,
    [DESCRIPTION]                            NVARCHAR (255)  NULL,
    [CREATEDDATE]                            DATETIME        NULL,
    [CREATEDBYID]                            NVARCHAR (18)   NULL,
    [LASTMODIFIEDDATE]                       DATETIME        NULL,
    [LASTMODIFIEDBYID]                       NVARCHAR (18)   NULL,
    [SYSTEMMODSTAMP]                         DATETIME        NULL,
    [ISDELETED]                              INT             NULL,
    [CONNECTIONRECEIVEDID]                   NVARCHAR (18)   NULL,
    [CONNECTIONSENTID]                       NVARCHAR (18)   NULL,
    [RELATED_SW_APPL_ITEM_TOTAL_STORAGE__C]  NVARCHAR (30)   NULL,
    [BILLING_TERM__C]                        NVARCHAR (1300) NULL,
    [COMPLEX_LINE_ITEM_INDEX__C]             DECIMAL (18)    NULL,
    [CUSTOM_PRICEBOOK_ENTRY__C]              NVARCHAR (18)   NULL,
    [CARBONITE_CONTRACT_LINE__C]             INT             NULL,
    [FREEFORMDISCOUNT__C]                    DECIMAL (5, 2)  NULL,
    [ISINCLUDED__C]                          INT             NULL,
    [IS_COMPLEX_PRODUCT__C]                  DECIMAL (18)    NULL,
    [SEAGATE_CONTRACT_LINE__C]               INT             NULL,
    [LICENSE_TYPE_ID__C]                     DECIMAL (18)    NULL,
    [LIST_PRICE__C]                          DECIMAL (18, 2) NULL,
    [NOOFMAILBOXES__C]                       DECIMAL (18)    NULL,
    [PARENT_ID__C]                           NVARCHAR (18)   NULL,
    [PARENT_NAME__C]                         NVARCHAR (255)  NULL,
    [PRODUCT_FAMILY__C]                      NVARCHAR (1300) NULL,
    [PRODUCT_NAME__C]                        NVARCHAR (1300) NULL,
    [PROMOTIONDISCOUNT__C]                   DECIMAL (5, 2)  NULL,
    [QUOTE_LINE_ITEM_ID__C]                  NVARCHAR (255)  NULL,
    [RELAYWARE_ID__C]                        NVARCHAR (18)   NULL,
    [STORAGEAMOUNTINGB__C]                   DECIMAL (18, 2) NULL,
    [STORAGEAMOUNT__C]                       DECIMAL (18, 2) NULL,
    [STORAGE_UOM__C]                         NVARCHAR (1300) NULL,
    [NETSUITE_QUOTE__C]                      INT             NULL,
    [TERMINMONTHS__C]                        DECIMAL (18)    NULL,
    [BILLING_ID__C]                          NVARCHAR (20)   NULL,
    [BILLING_INTERVAL__C]                    NVARCHAR (40)   NULL,
    [CONTRACT_LINE_ITEM__C]                  NVARCHAR (18)   NULL,
    [CONTRACT_RATE__C]                       DECIMAL (7, 2)  NULL,
    [EVAULT_LIST_PRICE__C]                   DECIMAL (18, 4) NULL,
    [END_DATE__C]                            DATETIME        NULL,
    [INCLUDED_STORAGE_TOTAL__C]              DECIMAL (18)    NULL,
    [INCLUDED_STORAGE__C]                    DECIMAL (9)     NULL,
    [INITIAL_DISCOUNT__C]                    DECIMAL (18, 2) NULL,
    [LINE_ID__C]                             DECIMAL (18)    NULL,
    [LINE_ITEM_MRR__C]                       DECIMAL (11, 2) NULL,
    [LINE_ITEM_TAV__C]                       DECIMAL (18, 2) NULL,
    [LINE_ITEM_TCV__C]                       DECIMAL (9)     NULL,
    [LINE_LEVEL_NON_MRR__C]                  DECIMAL (11, 2) NULL,
    [NETSUITE_ID_CONTRACT_LINE__C]           NVARCHAR (15)   NULL,
    [NETSUITE_ID__C]                         NVARCHAR (15)   NULL,
    [ORIGINAL_LIST_PRICE__C]                 DECIMAL (18, 2) NULL,
    [OVERAGE_DISCOUNT_PERCENT__C]            DECIMAL (5, 2)  NULL,
    [OVERAGE_LIST_RATE__C]                   DECIMAL (13, 4) NULL,
    [OVERAGE_NET_RATE__C]                    DECIMAL (13, 4) NULL,
    [PARENT_LINE_ID__C]                      DECIMAL (18)    NULL,
    [PRODUCT_CODE_SKU__C]                    NVARCHAR (40)   NULL,
    [PRODUCT_TYPE__C]                        NVARCHAR (40)   NULL,
    [QUOTE_DISCOUNT__C]                      DECIMAL (11, 8) NULL,
    [QUOTE_LINE_TRANSACTION_TYPE__C]         NVARCHAR (255)  NULL,
    [QUOTE_QUANTITY__C]                      DECIMAL (12, 2) NULL,
    [RE_CONTRACT__C]                         INT             NULL,
    [RELATED_SW_APPLIANCE_DESCRIPTION__C]    NVARCHAR (255)  NULL,
    [RELATED_SW_APPLIANCE_ITEM_SKU__C]       NVARCHAR (40)   NULL,
    [RELATED_SW_APPLIANCE_ITEM__C]           NVARCHAR (18)   NULL,
    [RELATED_SW_APPLIANCE_PURCHASE_PRICE__C] DECIMAL (10, 2) NULL,
    [SERVER_COUNT__C]                        DECIMAL (4)     NULL,
    [START_DATE__C]                          DATETIME        NULL,
    [TCC_AMOUNT__C]                          DECIMAL (11, 2) NULL,
    [TOTAL_PRICE__C]                         DECIMAL (18, 4) NULL,
    [UNIT_SALES_PRICE__C]                    DECIMAL (18, 4) NULL,
    [QUOTE_ACTION__C]                        NVARCHAR (30)   NULL,
    [PROMOTION_DISC__C]                      DECIMAL (18, 2) NULL,
    [PROMOTION_FLAG__C]                      INT             NULL,
    [PROMOTION_MINIMUM_QUANTITY__C]          DECIMAL (10)    NULL,
    [PROMOTION_OVERAGE_FEE_DISCOUNT__C]      DECIMAL (18, 2) NULL,
    [PROMOTION_QUANTITY__C]                  DECIMAL (10)    NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191509327EV_SF_OPPORTUNIT]
    ON [dbo].[EV_SF_OPPORTUNITYLINEITEM]([ID] ASC);

