CREATE TABLE [dbo].[EV_SF_PRODUCT2] (
    [ID]                                 NVARCHAR (18)   NULL,
    [NAME]                               NVARCHAR (255)  NULL,
    [PRODUCTCODE]                        NVARCHAR (255)  NULL,
    [DESCRIPTION]                        NVARCHAR (4000) NULL,
    [ISACTIVE]                           INT             NULL,
    [CREATEDDATE]                        DATETIME        NULL,
    [CREATEDBYID]                        NVARCHAR (18)   NULL,
    [LASTMODIFIEDDATE]                   DATETIME        NULL,
    [LASTMODIFIEDBYID]                   NVARCHAR (18)   NULL,
    [SYSTEMMODSTAMP]                     DATETIME        NULL,
    [FAMILY]                             NVARCHAR (40)   NULL,
    [CURRENCYISOCODE]                    NVARCHAR (3)    NULL,
    [ISDELETED]                          INT             NULL,
    [LASTVIEWEDDATE]                     DATETIME        NULL,
    [LASTREFERENCEDDATE]                 DATETIME        NULL,
    [CONNECTIONRECEIVEDID]               NVARCHAR (18)   NULL,
    [CONNECTIONSENTID]                   NVARCHAR (18)   NULL,
    [COUNT_OF_INCLUDED_ITEMS__C]         DECIMAL (3)     NULL,
    [INCLUDEDSTORAGEAMOUNTINGB__C]       DECIMAL (18, 2) NULL,
    [INCLUDED_MAILBOXES__C]              DECIMAL (18)    NULL,
    [INCLUDED_STORAGE_AMOUNT__C]         DECIMAL (18, 2) NULL,
    [ISINCLUDEABLE__C]                   INT             NULL,
    [IS_COMPLEX_PRODUCT__C]              INT             NULL,
    [IS_CONFIGURABLE__C]                 INT             NULL,
    [IS_CONVERTIBLE__C]                  INT             NULL,
    [IS_DISCOUNTABLE__C]                 INT             NULL,
    [LICENSE_TYPE_ID__C]                 DECIMAL (18)    NULL,
    [PRODUCTSKU__C]                      NVARCHAR (255)  NULL,
    [ADD_CAPACITY__C]                    INT             NULL,
    [STORAGE_UOM__C]                     NVARCHAR (255)  NULL,
    [SUB_LICENSE_TYPE_ID__C]             DECIMAL (18)    NULL,
    [TERM_IN_MONTHS__C]                  DECIMAL (18)    NULL,
    [TAV_CATEGORY__C]                    NVARCHAR (255)  NULL,
    [BOOKING_PRODUCT_GROUP__C]           NVARCHAR (255)  NULL,
    [BOOKING_COLUMNS__C]                 NVARCHAR (255)  NULL,
    [ADD_ON_PRODUCT__C]                  INT             NULL,
    [BUNDLE_COMPONENT_TAV_BREAKOUT__C]   NVARCHAR (255)  NULL,
    [CHARGE_TYPE__C]                     NVARCHAR (255)  NULL,
    [CONTRACT_BILLING_FREQUENCY__C]      NVARCHAR (255)  NULL,
    [CONTRACT_ITEM__C]                   INT             NULL,
    [CUSTOM_QTY_PRICING__C]              INT             NULL,
    [EXCLUDE_FROM_PRODUCT_SELECTION__C]  INT             NULL,
    [LICENSE_KEY_REQUIRED__C]            INT             NULL,
    [LOCK_QUANTITY__C]                   INT             NULL,
    [NETSUITE_ID__C]                     NVARCHAR (15)   NULL,
    [PRICING_GROUP__C]                   NVARCHAR (255)  NULL,
    [PRODUCT_CODE_SKU__C]                NVARCHAR (50)   NULL,
    [PRODUCT_IS_CONFIGURABLE__C]         INT             NULL,
    [PRODUCT_TYPE__C]                    NVARCHAR (255)  NULL,
    [REPORTING_CATEGORY__C]              NVARCHAR (80)   NULL,
    [REQUIRED_SERIAL_NO__C]              INT             NULL,
    [SW_S_M_REQUIRED__C]                 INT             NULL,
    [SALES_PRODUCT_GROUP__C]             NVARCHAR (255)  NULL,
    [SALES_PRODUCT_TYPE__C]              NVARCHAR (255)  NULL,
    [SEEDING_AMT_REQD__C]                INT             NULL,
    [SERVER_COUNT_REQUIRED__C]           INT             NULL,
    [SERVER_ENV_REQUIRED__C]             INT             NULL,
    [SHIPPING_REQUIRED__C]               INT             NULL,
    [SORT_ORDER__C]                      NVARCHAR (20)   NULL,
    [STORAGE_TYPE__C]                    NVARCHAR (255)  NULL,
    [SUBSCRIPTION_BUNDLE__C]             INT             NULL,
    [TIERED_PRODUCT__C]                  INT             NULL,
    [USAGE_UNIT__C]                      NVARCHAR (50)   NULL,
    [DATA_EXPORT__C]                     INT             NULL,
    [ORIGINAL_NS_INTERNAL_ID__C]         NVARCHAR (8)    NULL,
    [OVERAGE_NEXT_INCREMENT__C]          INT             NULL,
    [PRODUCT_CHANGE_WITHIN_FAMILY__C]    INT             NULL,
    [PRODUCT_IS_TRIAL__C]                INT             NULL,
    [SALES_PRODUCT_FAMILY__C]            NVARCHAR (255)  NULL,
    [TERM_BASED_SUBSCRIPTION__C]         INT             NULL,
    [EQUIVALENT_SW_PRODUCT__C]           NVARCHAR (18)   NULL,
    [BASE_UOM__C]                        NVARCHAR (4)    NULL,
    [MATERIAL_CUSTOMER__C]               NVARCHAR (200)  NULL,
    [MATERIAL_GROUP__C]                  NVARCHAR (100)  NULL,
    [MATERIAL_STATUS__C]                 NVARCHAR (2)    NULL,
    [PRODUCT_FAMILY__C]                  NVARCHAR (100)  NULL,
    [MATERIAL__C]                        NVARCHAR (36)   NULL,
    [CALC_TOTAL_STORAGE_NON_CUST_QTY__C] INT             NULL,
    [DO_NOT_ROUND_PRICE_TO_2__C]         INT             NULL,
    [REQUIRED_CORE__C]                   INT             NULL,
    [REQUIRED_CHILD__C]                  INT             NULL,
    [TERMINATION_FEE__C]                 INT             NULL,
    [DMA_AUTO_PROVISIONING__C]           INT             NULL,
    [REQUIRED_SW_SUBSCRIPTION_ITEM__C]   NVARCHAR (18)   NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191501999EV_SF_PRODUCT2_I]
    ON [dbo].[EV_SF_PRODUCT2]([ID] ASC);

