CREATE TABLE [dbo].[EV_SF_CONTRACT] (
    [ID]                                       NVARCHAR (18)    NULL,
    [ACCOUNTID]                                NVARCHAR (18)    NULL,
    [CURRENCYISOCODE]                          NVARCHAR (3)     NULL,
    [OWNEREXPIRATIONNOTICE]                    NVARCHAR (40)    NULL,
    [STARTDATE]                                DATETIME         NULL,
    [ENDDATE]                                  DATETIME         NULL,
    [BILLINGSTREET]                            NVARCHAR (255)   NULL,
    [BILLINGCITY]                              NVARCHAR (40)    NULL,
    [BILLINGSTATE]                             NVARCHAR (80)    NULL,
    [BILLINGPOSTALCODE]                        NVARCHAR (20)    NULL,
    [BILLINGCOUNTRY]                           NVARCHAR (80)    NULL,
    [BILLINGLATITUDE]                          DECIMAL (18, 15) NULL,
    [BILLINGLONGITUDE]                         DECIMAL (18, 15) NULL,
    [SHIPPINGSTREET]                           NVARCHAR (255)   NULL,
    [SHIPPINGCITY]                             NVARCHAR (40)    NULL,
    [SHIPPINGSTATE]                            NVARCHAR (80)    NULL,
    [SHIPPINGPOSTALCODE]                       NVARCHAR (20)    NULL,
    [SHIPPINGCOUNTRY]                          NVARCHAR (80)    NULL,
    [SHIPPINGLATITUDE]                         DECIMAL (18, 15) NULL,
    [SHIPPINGLONGITUDE]                        DECIMAL (18, 15) NULL,
    [OWNERID]                                  NVARCHAR (18)    NULL,
    [STATUS]                                   NVARCHAR (40)    NULL,
    [COMPANYSIGNEDID]                          NVARCHAR (18)    NULL,
    [COMPANYSIGNEDDATE]                        DATETIME         NULL,
    [CUSTOMERSIGNEDID]                         NVARCHAR (18)    NULL,
    [CUSTOMERSIGNEDTITLE]                      NVARCHAR (40)    NULL,
    [CUSTOMERSIGNEDDATE]                       DATETIME         NULL,
    [SPECIALTERMS]                             NVARCHAR (4000)  NULL,
    [ACTIVATEDBYID]                            NVARCHAR (18)    NULL,
    [ACTIVATEDDATE]                            DATETIME         NULL,
    [STATUSCODE]                               NVARCHAR (40)    NULL,
    [DESCRIPTION]                              NTEXT            NULL,
    [NAME]                                     NVARCHAR (80)    NULL,
    [ISDELETED]                                INT              NULL,
    [CONTRACTNUMBER]                           NVARCHAR (30)    NULL,
    [LASTAPPROVEDDATE]                         DATETIME         NULL,
    [CREATEDDATE]                              DATETIME         NULL,
    [CREATEDBYID]                              NVARCHAR (18)    NULL,
    [LASTMODIFIEDDATE]                         DATETIME         NULL,
    [LASTMODIFIEDBYID]                         NVARCHAR (18)    NULL,
    [SYSTEMMODSTAMP]                           DATETIME         NULL,
    [LASTACTIVITYDATE]                         DATETIME         NULL,
    [LASTVIEWEDDATE]                           DATETIME         NULL,
    [LASTREFERENCEDDATE]                       DATETIME         NULL,
    [SERVICE_PRODUCT_TERM__C]                  DECIMAL (10)     NULL,
    [DATED_EXCHANGE_RATE__C]                   DECIMAL (5, 4)   NULL,
    [BILL_TO_ERPID__C]                         NVARCHAR (1300)  NULL,
    [BILL_TO__C]                               NVARCHAR (255)   NULL,
    [BOOKING__C]                               NVARCHAR (18)    NULL,
    [CONTRACT_STATUS__C]                       NVARCHAR (255)   NULL,
    [CONTRACT_TERMINATION_DATE__C]             DATETIME         NULL,
    [CONTRACT_TYPE__C]                         NVARCHAR (1300)  NULL,
    [CONTRACT_UPLOAD_SOURCE__C]                NVARCHAR (255)   NULL,
    [DISTRIBUTOR_ORDER_NO__C]                  NVARCHAR (100)   NULL,
    [DISTRIBUTOR__C]                           NVARCHAR (18)    NULL,
    [ERPID_CUSTOMER__C]                        NVARCHAR (1300)  NULL,
    [ERPID_DISTRIBUTOR__C]                     NVARCHAR (1300)  NULL,
    [ERPID_REFERRAL_PARTNER__C]                NVARCHAR (1300)  NULL,
    [ERPID_RESELLER_PARTNER__C]                NVARCHAR (1300)  NULL,
    [ERP_ORDER_NO__C]                          NVARCHAR (150)   NULL,
    [HIDDEN_BILL_TO_GPID__C]                   NVARCHAR (25)    NULL,
    [HIDDEN_CONTRACT_CHANNEL__C]               NVARCHAR (255)   NULL,
    [INSTALLATION_DATE__C]                     DATETIME         NULL,
    [LEGACY_CONTRACT_NUMBER__C]                NVARCHAR (120)   NULL,
    [MAS_NOTES__C]                             NVARCHAR (1000)  NULL,
    [MONTHLY_MINIMUM__C]                       DECIMAL (12, 2)  NULL,
    [ORDER_NO__C]                              NVARCHAR (100)   NULL,
    [ORDER_TYPE__C]                            NVARCHAR (255)   NULL,
    [ORDERED_DATE__C]                          DATETIME         NULL,
    [REOPEN_REASON__C]                         NVARCHAR (255)   NULL,
    [REFERRAL_PARTNER_NAME__C]                 NVARCHAR (18)    NULL,
    [RELATED_CONTRACT__C]                      NVARCHAR (18)    NULL,
    [RESELLER_PARTNER_NAME__C]                 NVARCHAR (18)    NULL,
    [OPEN_SERVICE_PRODUCT_COUNT__C]            DECIMAL (18)     NULL,
    [TAV__C]                                   DECIMAL (12, 2)  NULL,
    [RESELLER_CONTACT__C]                      NVARCHAR (18)    NULL,
    [TCV__C]                                   DECIMAL (12, 2)  NULL,
    [BILL_TO_ACCOUNT__C]                       NVARCHAR (18)    NULL,
    [TOTAL_GROSS__C]                           DECIMAL (12, 2)  NULL,
    [TOTAL_MRR_GROSS__C]                       DECIMAL (12, 2)  NULL,
    [TOTAL_NRR_GROSS__C]                       DECIMAL (12, 2)  NULL,
    [DAYS_REMAINING__C]                        DECIMAL (18)     NULL,
    [ACTIVE_SERVICE_PRODUCT_COUNT__C]          DECIMAL (18)     NULL,
    [MAX_PRODUCT_TERM__C]                      DECIMAL (10)     NULL,
    [S_M_CONTRACT_TERM__C]                     DECIMAL (10)     NULL,
    [SW_HW_PRODUCT_COUNT__C]                   DECIMAL (18)     NULL,
    [ACTIVATED_DATE_TIME__C]                   DATETIME         NULL,
    [ACCOUNT_VAULT__C]                         NVARCHAR (18)    NULL,
    [TERMINATED_DATE_TIME__C]                  DATETIME         NULL,
    [CUSTOMER_MASID__C]                        NVARCHAR (1300)  NULL,
    [HIDDEN_EARLIEST_SERVICE_CP_START_DATE__C] DATETIME         NULL,
    [HIDDEN_COUNT_OF_NULL_MRR_COMMITTED_GB__C] DECIMAL (18)     NULL,
    [END_DATE__C]                              DATETIME         NULL,
    [START_DATE__C]                            DATETIME         NULL,
    [NS_CONTRACT_INTERNAL_ID__C]               NVARCHAR (20)    NULL,
    [RESELLER_ACCOUNT__C]                      NVARCHAR (18)    NULL,
    [SHIP_TO_CUSTOMER__C]                      NVARCHAR (18)    NULL,
    [BILL_TO_ACCOUNT_TYPE__C]                  NVARCHAR (1300)  NULL,
    [RELAYWARE_ID__C]                          DECIMAL (18)     NULL,
    [ORIGINAL_NS_CONTRACT_INTERNAL_ID__C]      NVARCHAR (20)    NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191519669EV_SF_CONTRACT_I]
    ON [dbo].[EV_SF_CONTRACT]([ID] ASC);

