CREATE TABLE [dbo].[EV_SF_LEAD] (
    [ID]                                          NVARCHAR (18)    NULL,
    [ISDELETED]                                   INT              NULL,
    [MASTERRECORDID]                              NVARCHAR (18)    NULL,
    [LASTNAME]                                    NVARCHAR (80)    NULL,
    [FIRSTNAME]                                   NVARCHAR (40)    NULL,
    [SALUTATION]                                  NVARCHAR (40)    NULL,
    [NAME]                                        NVARCHAR (121)   NULL,
    [RECORDTYPEID]                                NVARCHAR (18)    NULL,
    [TITLE]                                       NVARCHAR (128)   NULL,
    [COMPANY]                                     NVARCHAR (255)   NULL,
    [STREET]                                      NVARCHAR (255)   NULL,
    [CITY]                                        NVARCHAR (40)    NULL,
    [STATE]                                       NVARCHAR (80)    NULL,
    [POSTALCODE]                                  NVARCHAR (20)    NULL,
    [COUNTRY]                                     NVARCHAR (80)    NULL,
    [LATITUDE]                                    DECIMAL (18, 15) NULL,
    [LONGITUDE]                                   DECIMAL (18, 15) NULL,
    [PHONE]                                       NVARCHAR (40)    NULL,
    [EMAIL]                                       NVARCHAR (80)    NULL,
    [WEBSITE]                                     NVARCHAR (255)   NULL,
    [PHOTOURL]                                    NVARCHAR (255)   NULL,
    [DESCRIPTION]                                 NTEXT            NULL,
    [LEADSOURCE]                                  NVARCHAR (40)    NULL,
    [STATUS]                                      NVARCHAR (40)    NULL,
    [INDUSTRY]                                    NVARCHAR (40)    NULL,
    [RATING]                                      NVARCHAR (40)    NULL,
    [CURRENCYISOCODE]                             NVARCHAR (3)     NULL,
    [ANNUALREVENUE]                               DECIMAL (18)     NULL,
    [NUMBEROFEMPLOYEES]                           INT              NULL,
    [OWNERID]                                     NVARCHAR (18)    NULL,
    [ISCONVERTED]                                 INT              NULL,
    [CONVERTEDDATE]                               DATETIME         NULL,
    [CONVERTEDACCOUNTID]                          NVARCHAR (18)    NULL,
    [CONVERTEDCONTACTID]                          NVARCHAR (18)    NULL,
    [CONVERTEDOPPORTUNITYID]                      NVARCHAR (18)    NULL,
    [ISUNREADBYOWNER]                             INT              NULL,
    [CREATEDDATE]                                 DATETIME         NULL,
    [CREATEDBYID]                                 NVARCHAR (18)    NULL,
    [LASTMODIFIEDDATE]                            DATETIME         NULL,
    [LASTMODIFIEDBYID]                            NVARCHAR (18)    NULL,
    [SYSTEMMODSTAMP]                              DATETIME         NULL,
    [LASTACTIVITYDATE]                            DATETIME         NULL,
    [LASTVIEWEDDATE]                              DATETIME         NULL,
    [LASTREFERENCEDDATE]                          DATETIME         NULL,
    [PARTNERACCOUNTID]                            NVARCHAR (18)    NULL,
    [JIGSAW]                                      NVARCHAR (20)    NULL,
    [JIGSAWCONTACTID]                             NVARCHAR (20)    NULL,
    [CONNECTIONRECEIVEDID]                        NVARCHAR (18)    NULL,
    [CONNECTIONSENTID]                            NVARCHAR (18)    NULL,
    [EMAILBOUNCEDREASON]                          NVARCHAR (255)   NULL,
    [EMAILBOUNCEDDATE]                            DATETIME         NULL,
    [SFGA__CORRELATIONID__C]                      NVARCHAR (255)   NULL,
    [SFGA__CORRELATION_DATA__C]                   NTEXT            NULL,
    [SFGA__WEB_SOURCE__C]                         NVARCHAR (255)   NULL,
    [COMPANY_SIZE__C]                             NVARCHAR (30)    NULL,
    [LEAD_SUBMITTED_BY__C]                        NVARCHAR (100)   NULL,
    [PHONE_DIRECT__C]                             NVARCHAR (40)    NULL,
    [TERRITORY__C]                                NVARCHAR (255)   NULL,
    [NUMBER_OF_SERVERS__C]                        DECIMAL (10)     NULL,
    [AMOUNT_OF_DATA_GB__C]                        DECIMAL (10)     NULL,
    [WORKING_WITH_PARTNER__C]                     NVARCHAR (255)   NULL,
    [PARTNER_NAME__C]                             NVARCHAR (50)    NULL,
    [MKTO2__INFERRED_CITY__C]                     NVARCHAR (255)   NULL,
    [MKTO2__INFERRED_COMPANY__C]                  NVARCHAR (255)   NULL,
    [MKTO2__INFERRED_COUNTRY__C]                  NVARCHAR (255)   NULL,
    [MKTO2__INFERRED_METROPOLITAN_AREA__C]        NVARCHAR (255)   NULL,
    [MKTO2__INFERRED_PHONE_AREA_CODE__C]          NVARCHAR (255)   NULL,
    [MKTO2__INFERRED_POSTAL_CODE__C]              NVARCHAR (255)   NULL,
    [MKTO2__INFERRED_STATE_REGION__C]             NVARCHAR (255)   NULL,
    [MKTO2__LEAD_SCORE__C]                        DECIMAL (18)     NULL,
    [MKTO2__ORIGINAL_REFERRER__C]                 NVARCHAR (255)   NULL,
    [MKTO2__ORIGINAL_SEARCH_ENGINE__C]            NVARCHAR (255)   NULL,
    [MKTO2__ORIGINAL_SEARCH_PHRASE__C]            NVARCHAR (255)   NULL,
    [MKTO2__ORIGINAL_SOURCE_INFO__C]              NVARCHAR (2000)  NULL,
    [MKTO2__ORIGINAL_SOURCE_TYPE__C]              NVARCHAR (255)   NULL,
    [LEAD_AGE__C]                                 DECIMAL (18)     NULL,
    [REASON_UNQUALIFIED__C]                       NVARCHAR (255)   NULL,
    [COMPELLING_EVENT__C]                         NVARCHAR (255)   NULL,
    [WHAT_ARE_THEY_USING_TODAY__C]                NVARCHAR (255)   NULL,
    [HOW_MANY_LOCATIONS__C]                       NVARCHAR (255)   NULL,
    [TIMEFRAME_FOR_DECISION__C]                   NVARCHAR (255)   NULL,
    [SCHEDULED_PROJECT__C]                        NVARCHAR (255)   NULL,
    [IS_THERE_A_BUDGETED_PROJECT__C]              NVARCHAR (255)   NULL,
    [DECISION_MAKER__C]                           NVARCHAR (18)    NULL,
    [LEAD_SOURCE_DETAIL__C]                       NVARCHAR (255)   NULL,
    [SUMMARY_INFORMATION__C]                      NVARCHAR (1000)  NULL,
    [PARTNER_ACCOUNT__C]                          NVARCHAR (18)    NULL,
    [PARTNER_CONTACT_NAME__C]                     NVARCHAR (18)    NULL,
    [PARTNER__C]                                  NVARCHAR (80)    NULL,
    [PARTNER_PHONE__C]                            NVARCHAR (40)    NULL,
    [EXPECTED_CLOSE_DATE__C]                      DATETIME         NULL,
    [DEAL_SIZE__C]                                DECIMAL (18, 2)  NULL,
    [PRODUCT_INTERESTS__C]                        NTEXT            NULL,
    [ART_POTENTIAL_PARTNER__C]                    NVARCHAR (1300)  NULL,
    [APPROVAL_STATUS__C]                          NVARCHAR (255)   NULL,
    [DAYS_LEFT_UNTIL_EXPIRY__C]                   DECIMAL (18)     NULL,
    [DEAL_APPROVED_DATE__C]                       DATETIME         NULL,
    [DEAL_ID__C]                                  NVARCHAR (30)    NULL,
    [DEAL_REGISTRATION_EXPIRATION__C]             DATETIME         NULL,
    [MKTO_SI__LAST_INTERESTING_MOMENT_DATE__C]    DATETIME         NULL,
    [MKTO_SI__LAST_INTERESTING_MOMENT_DESC__C]    NVARCHAR (255)   NULL,
    [MKTO_SI__LAST_INTERESTING_MOMENT_SOURCE__C]  NVARCHAR (100)   NULL,
    [MKTO_SI__LAST_INTERESTING_MOMENT_TYPE__C]    NVARCHAR (100)   NULL,
    [MKTO_SI__LAST_INTERESTING_MOMENT__C]         NVARCHAR (1300)  NULL,
    [MKTO_SI__PRIORITY__C]                        DECIMAL (18)     NULL,
    [MKTO_SI__RELATIVE_SCORE_VALUE__C]            DECIMAL (4)      NULL,
    [MKTO_SI__RELATIVE_SCORE__C]                  NVARCHAR (1300)  NULL,
    [MKTO_SI__URGENCY_VALUE__C]                   DECIMAL (4)      NULL,
    [MKTO_SI__URGENCY__C]                         NVARCHAR (1300)  NULL,
    [MKTO_SI__VIEW_IN_MARKETO__C]                 NVARCHAR (1300)  NULL,
    [DEAL_SUBMISSION_DATE__C]                     DATETIME         NULL,
    [PARTNER_CATEGORY__C]                         NVARCHAR (255)   NULL,
    [PARTNER_MANAGER_EMAIL_ADDRESS__C]            NVARCHAR (80)    NULL,
    [COMPANY_EMAIL__C]                            NVARCHAR (80)    NULL,
    [PARTNER_TYPE__C]                             NVARCHAR (255)   NULL,
    [REASON_UNQUALIFIED_COMPETITOR__C]            NVARCHAR (255)   NULL,
    [PARTNER_ACCOUNT_NAME__C]                     NVARCHAR (1300)  NULL,
    [PARTNER_NOTES__C]                            NTEXT            NULL,
    [EMAIL_OPT_IN__C]                             INT              NULL,
    [DEMOGRAPHIC_SCORE__C]                        DECIMAL (18)     NULL,
    [MICROSOFT_INFLUENCED__C]                     NVARCHAR (255)   NULL,
    [ORIGINAL_LEAD_SOURCE_DETAIL__C]              NVARCHAR (255)   NULL,
    [LEAD_SOURCE_DETAIL_FOR_CONTACT__C]           NVARCHAR (1300)  NULL,
    [PARTNER_SOURCED_BY_MARKETO__C]               NVARCHAR (255)   NULL,
    [QBDIALER__DIALS__C]                          DECIMAL (18)     NULL,
    [QBDIALER__LASTCALLTIME__C]                   DATETIME         NULL,
    [QBDIALER__RESPONSETIME__C]                   DECIMAL (18)     NULL,
    [EVAULT_NEWSLETTERS_LIST__C]                  INT              NULL,
    [EVAULT_SPECIAL_OFFERS_LIST__C]               INT              NULL,
    [PARTNER_NEWSLETTERS_LIST__C]                 INT              NULL,
    [PARTNER_SPECIAL_OFFERS_LIST__C]              INT              NULL,
    [I__CREATEDFORUSER__C]                        NVARCHAR (18)    NULL,
    [I__OTHEREMAILS__C]                           NVARCHAR (2048)  NULL,
    [HIDDEN_CONVERTED_LEAD_CONTACT__C]            INT              NULL,
    [HIDDEN_CONVERTED_LEAD_OPPORTUNITY__C]        INT              NULL,
    [HIDDEN_ORIGINAL_LEAD_SOURCE_OPP__C]          NVARCHAR (1300)  NULL,
    [HIDDEN_ORIGINAL_LEAD_SOURCE_DETAIL_OPP__C]   NVARCHAR (1300)  NULL,
    [TERRITORY_TAM__C]                            NVARCHAR (255)   NULL,
    [MKTO_SI__HIDEDATE__C]                        DATETIME         NULL,
    [LDR_WATCH_LIST__C]                           INT              NULL,
    [LDR_NOTES__C]                                NVARCHAR (250)   NULL,
    [LEADCOMMENTS__C]                             NVARCHAR (2500)  NULL,
    [X1_HOW_OFTEN_DOES_YOUR_COMPANY_DO_A_FULL__C] NVARCHAR (255)   NULL,
    [X2_WHAT_IS_THE_PRIMARY_TYPE_OF_BACKUP_TH__C] NVARCHAR (255)   NULL,
    [X3_WHAT_IS_THE_PRIMARY_MECHANISM_TO_GET__C]  NVARCHAR (255)   NULL,
    [HOW_OFTEN__C]                                NVARCHAR (255)   NULL,
    [X5_WHAT_RESOURCES_DO_YOU_USE_TO_TAKE_BAC__C] NVARCHAR (255)   NULL,
    [X6_HOW_FAR_AWAY_IS_YOUR_BACKUP_DATA_STOR__C] NVARCHAR (255)   NULL,
    [X7_DOES_YOUR_COMPANY_ENCRYPT_YOUR_BACKUP__C] NVARCHAR (255)   NULL,
    [X8_DOES_YOUR_COMPANY_HAVE_A_DOCUMENTED_D__C] NVARCHAR (255)   NULL,
    [X9_HOW_OFTEN_DOES_YOUR_COMPANY_TEST_YOUR__C] NVARCHAR (255)   NULL,
    [X10_DO_YOU_HAVE_A_DOCUMENTED_RECOVERY_TI__C] NVARCHAR (255)   NULL,
    [X11_DID_YOU_MEET_YOUR_RECOVERY_TIME_OBJE__C] NVARCHAR (255)   NULL,
    [X12_DO_YOU_HAVE_A_DESIGNATED_DR_FACILITY__C] NVARCHAR (255)   NULL,
    [X13_WHAT_IS_THE_DISTANCE_TO_THE_FACILITY__C] NVARCHAR (255)   NULL,
    [X14_IS_YOUR_DISASTER_RECOVERY_FACILITY__C]   NVARCHAR (255)   NULL,
    [X15_WHO_WOULD_PERFORM_THE_RECOVERY_AT_TH__C] NVARCHAR (255)   NULL,
    [X16_ASSESSMENT_SCORE__C]                     DECIMAL (10)     NULL,
    [X17_DRS__C]                                  DECIMAL (10)     NULL,
    [AGREE_TO_SAAS_FREEMIUM_TERMS__C]             INT              NULL,
    [LEAD_DISTRIBUTION_CONTACT__C]                NVARCHAR (18)    NULL,
    [LEAD_DISTRIBUTION_CONTACT_EMAIL__C]          NVARCHAR (80)    NULL,
    [PARTNER_ACCOUNT_OWNER_EMAIL__C]              NVARCHAR (80)    NULL,
    [LEAD_AGE_2__C]                               DECIMAL (18)     NULL,
    [MARKETING_QUALIFIED__C]                      INT              NULL,
    [MARKETING_NURTURE__C]                        INT              NULL,
    [LDR_REJECTED__C]                             INT              NULL,
    [SALES_REJECTED__C]                           INT              NULL,
    [AUTO_RECYCLED__C]                            INT              NULL,
    [SCORE_QUALIFIED__C]                          INT              NULL,
    [MQL_RECENT__C]                               DATETIME         NULL,
    [MQL_ORIGINAL_DATE__C]                        DATETIME         NULL,
    [NURTURE_RECENT__C]                           DATETIME         NULL,
    [MARKETING_NURTURE_ORIGINAL_DATE__C]          DATETIME         NULL,
    [LDR_RECENT__C]                               DATETIME         NULL,
    [LDR_REJECTED_ORIGINAL_DATE__C]               DATETIME         NULL,
    [REJECTED_REASON__C]                          NVARCHAR (255)   NULL,
    [OTHER_REJECTED_REASON__C]                    NVARCHAR (100)   NULL,
    [SALESREJ_RECENT__C]                          DATETIME         NULL,
    [SALES_REJECTED_ORIGINAL_DATE__C]             DATETIME         NULL,
    [SCOREQLFD_RECENT__C]                         DATETIME         NULL,
    [SCORE_QUALIFIED_ORIGINAL_DATE__C]            DATETIME         NULL,
    [AUTOREC_RECENT__C]                           DATETIME         NULL,
    [AUTO_RECYCLED_ORIGINAL_DATE__C]              DATETIME         NULL,
    [PRIOR_LEAD_STATUS__C]                        NVARCHAR (30)    NULL,
    [QUALIFIED_BY__C]                             NVARCHAR (35)    NULL,
    [QUALIFIED_BY_ROLE__C]                        NVARCHAR (35)    NULL,
    [LDR_REJECTED_BY__C]                          NVARCHAR (35)    NULL,
    [LDR_REJECTED_BY_ROLE__C]                     NVARCHAR (35)    NULL,
    [SALES_REJECTED_BY__C]                        NVARCHAR (35)    NULL,
    [SALES_REJECTED_BY_ROLE__C]                   NVARCHAR (35)    NULL,
    [WATERFALL_MOST_RECENT_DATE__C]               DATETIME         NULL,
    [ORIGINAL_LEAD_SOURCE__C]                     NVARCHAR (255)   NULL,
    [STRIKE_IRON_VALIDATION__C]                   NVARCHAR (255)   NULL,
    [STATUS_AGE__C]                               DECIMAL (18)     NULL,
    [GEO__C]                                      NVARCHAR (1300)  NULL,
    [INSIDEVIEW_ID__C]                            NVARCHAR (18)    NULL,
    [DEAL_REGISTRATION_NOTES__C]                  NVARCHAR (255)   NULL,
    [PARTNER_VIEWED__C]                           INT              NULL,
    [HIDDEN_LEAD_ID__C]                           NVARCHAR (1300)  NULL,
    [UTM_SOURCE__C]                               NVARCHAR (100)   NULL,
    [UTM_MEDIUM__C]                               NVARCHAR (100)   NULL,
    [UTM_TERM__C]                                 NVARCHAR (100)   NULL,
    [UTM_CAMPAIGN__C]                             NVARCHAR (100)   NULL,
    [VAT_NUMBER__C]                               NVARCHAR (50)    NULL,
    [PARTNER_PORTAL_JOB_FUNCTION__C]              NTEXT            NULL,
    [WORKING_WITH_EVAULT_HEALTHCARE_REP__C]       INT              NULL,
    [NAICS_CODE__C]                               NVARCHAR (255)   NULL,
    [RELAYWARE_ID__C]                             DECIMAL (18)     NULL,
    [RESELLER_ACCOUNT__C]                         NVARCHAR (18)    NULL,
    [DISTRIBUTOR_ACCOUNT__C]                      NVARCHAR (18)    NULL,
    [RESELLER_CONTACT__C]                         NVARCHAR (18)    NULL,
    [DISTRIBUTOR_CONTACT__C]                      NVARCHAR (18)    NULL,
    [RESELLER_CONTACT_EMAIL__C]                   NVARCHAR (80)    NULL,
    [DISTRIBUTOR_CONTACT_EMAIL__C]                NVARCHAR (80)    NULL,
    [PARTNER_ACCOUNT_GEO__C]                      NVARCHAR (1300)  NULL,
    [OWNER_SALES_ORG__C]                          NVARCHAR (1300)  NULL,
    [HIDDEN_LEAD_ID_ACCOUNT__C]                   NVARCHAR (1300)  NULL,
    [HIDDEN_LEAD_ID_CONTACT__C]                   NVARCHAR (1300)  NULL,
    [INDUSTRY_SPECIALIZATION__C]                  NTEXT            NULL,
    [HIDDEN_LEAD_RECORD_TYPE__C]                  NVARCHAR (255)   NULL,
    [I__DAYSSINCELASTMAIL__C]                     DECIMAL (18)     NULL,
    [I__LASTINBOUNDMAIL__C]                       NVARCHAR (18)    NULL,
    [I__LASTINBOUNDSENT__C]                       DATETIME         NULL,
    [I__LASTINBOUNDTIME__C]                       DATETIME         NULL,
    [I__LASTMAILSENT__C]                          DATETIME         NULL,
    [I__LASTMAILTIMEDELTA__C]                     DECIMAL (18)     NULL,
    [I__LASTMAILTIME__C]                          DATETIME         NULL,
    [I__LASTMAIL__C]                              NVARCHAR (18)    NULL,
    [I__LASTOUTBOUNDMAIL__C]                      NVARCHAR (18)    NULL,
    [I__LASTOUTBOUNDSENT__C]                      DATETIME         NULL,
    [I__LASTOUTBOUNDTIME__C]                      DATETIME         NULL,
    [LATTICE_SCORE__C]                            NVARCHAR (5)     NULL,
    [PROGRAM_PROMOTION__C]                        NVARCHAR (255)   NULL,
    [LATTICE_LEAD_INSIGHT_ONE__C]                 DECIMAL (18)     NULL,
    [LATTICE_LEAD_INSIGHT_TWO__C]                 DECIMAL (18)     NULL,
    [LATTICE_LEAD_INSIGHT_THREE__C]               DECIMAL (18)     NULL,
    [LATTICE_LEAD_INSIGHT_FOUR__C]                DECIMAL (18)     NULL,
    [LATTICE_LEAD_INSIGHT_FIVE__C]                DECIMAL (18)     NULL,
    [LATTICE_LEAD_SCORE_DATE__C]                  DATETIME         NULL,
    [QUALIFYING_LEVEL__C]                         NVARCHAR (255)   NULL,
    [MQL_NOTES__C]                                NTEXT            NULL,
    [CONVERTING_LEAD_SOURCE_DETAI__C]             NVARCHAR (20)    NULL,
    [QUALIFICATION_PATH__C]                       NVARCHAR (255)   NULL,
    [CONVERTING_LEAD_SOURCE_DETAIL__C]            NVARCHAR (20)    NULL,
    [LINE_OF_BUSINESS__C]                         NVARCHAR (255)   NULL,
    [QBDIALER__CLOSEDATE__C]                      DATETIME         NULL,
    [QBDIALER__CLOSESCORE__C]                     DECIMAL (9, 5)   NULL,
    [QBDIALER__CONTACTDATE__C]                    DATETIME         NULL,
    [QBDIALER__CONTACTSCOREID__C]                 NVARCHAR (18)    NULL,
    [QBDIALER__CONTACTSCORE__C]                   DECIMAL (9, 5)   NULL,
    [QBDIALER__TIMEZONESIDKEY__C]                 NVARCHAR (24)    NULL,
    [SIMPLE_TITLE__C]                             NVARCHAR (255)   NULL,
    [D_B_TITLE__C]                                NVARCHAR (255)   NULL,
    [CAMPAIGN_SOURCE__C]                          NVARCHAR (255)   NULL,
    [SEQUENTIAL_ID__C]                            NVARCHAR (255)   NULL,
    [YOUR_ROLE_IN_DECISION_MAKING__C]             NVARCHAR (255)   NULL,
    [MQL_CALL_DATE_TIME__C]                       DATETIME         NULL,
    [EMPLOYEE_RANGE__C]                           NVARCHAR (255)   NULL,
    [REVENUE_RANGE__C]                            NVARCHAR (255)   NULL,
    [SIC_CODE__C]                                 DECIMAL (18)     NULL,
    [SIC_DESCRIPTION__C]                          NVARCHAR (255)   NULL,
    [JOB_FUNCTION__C]                             NVARCHAR (255)   NULL,
    [JOB_LEVEL__C]                                NVARCHAR (255)   NULL,
    [GLOBAL_PRIMARY_8_DIGIT_SIC_DESCRIPTION__C]   DECIMAL (18)     NULL,
    [NAICS_6_DIGIT_DESCRIPTION__C]                NVARCHAR (255)   NULL,
    [LOCATION_TYPE__C]                            NVARCHAR (255)   NULL,
    [BARRACUDA__C]                                INT              NULL,
    [UNITRENDS__C]                                INT              NULL,
    [VEAM__C]                                     INT              NULL,
    [SYMANTEC__C]                                 INT              NULL,
    [NETAPP__C]                                   INT              NULL,
    [COMMVAULT__C]                                INT              NULL,
    [AVAMAR__C]                                   INT              NULL,
    [DATADOMAIN__C]                               INT              NULL,
    [TIVOLI__C]                                   INT              NULL,
    [NETBACKUP__C]                                INT              NULL,
    [IBM_I__C]                                    INT              NULL,
    [BUDGET_AMOUNT__C]                            NVARCHAR (255)   NULL,
    [INITIATIVE_DRIVERS__C]                       NVARCHAR (255)   NULL,
    [PROJECT_FUNDING_STATUS__C]                   NVARCHAR (255)   NULL,
    [PURCHASE_TIMELINE__C]                        NVARCHAR (255)   NULL,
    [NSQ_REASON__C]                               NVARCHAR (255)   NULL,
    [NETP_SPX__COMPANY_INDUSTRIES__C]             NTEXT            NULL,
    [NETP_SPX__COUNTY__C]                         NVARCHAR (255)   NULL,
    [NETP_SPX__CREATED_BY_SALESPROSPEX__C]        INT              NULL,
    [NETP_SPX__DEDUPEFIRSTLASTCOMPANY__C]         NVARCHAR (1300)  NULL,
    [NETP_SPX__DEDUPEFIRSTLASTEMAILDOMAIN__C]     NVARCHAR (1300)  NULL,
    [NETP_SPX__DEDUPEFIRSTLAST__C]                NVARCHAR (1300)  NULL,
    [NETP_SPX__FACEBOOK_PROFILE__C]               NVARCHAR (255)   NULL,
    [NETP_SPX__JOB_FUNCTION__C]                   NVARCHAR (255)   NULL,
    [NETP_SPX__JOB_LEVEL__C]                      NVARCHAR (255)   NULL,
    [NETP_SPX__LINKEDIN_PROFILE__C]               NVARCHAR (255)   NULL,
    [NETP_SPX__NETPROSPEX_ID__C]                  NVARCHAR (255)   NULL,
    [NETP_SPX__PHONE_2__C]                        NVARCHAR (40)    NULL,
    [NETP_SPX__SICCODE__C]                        NVARCHAR (15)    NULL,
    [NETP_SPX__SIC_CODES__C]                      NTEXT            NULL,
    [NETP_SPX__SIC_DESCRIPTION__C]                NVARCHAR (255)   NULL,
    [NETP_SPX__TECHPROSPEX__C]                    NVARCHAR (255)   NULL,
    [NETP_SPX__TWITTER_PROFILE__C]                NVARCHAR (255)   NULL,
    [MKTO_SI__ADD_TO_MARKETO_CAMPAIGN__C]         NVARCHAR (1300)  NULL,
    [MKTO_SI__MSICONTACTID__C]                    NVARCHAR (18)    NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191540858EV_SF_LEAD_ID]
    ON [dbo].[EV_SF_LEAD]([ID] ASC);

