CREATE TABLE [dbo].[EV_SF_OPPORTUNITY] (
    [ID]                                    NVARCHAR (18)   NULL,
    [ACCOUNTID]                             NVARCHAR (18)   NULL,
    [NAME]                                  NVARCHAR (120)  NULL,
    [STAGENAME]                             NVARCHAR (40)   NULL,
    [AMOUNT]                                DECIMAL (18, 2) NULL,
    [PROBABILITY]                           DECIMAL (3)     NULL,
    [CLOSEDATE]                             DATETIME        NULL,
    [ISCLOSED]                              INT             NULL,
    [CURRENCYISOCODE]                       NVARCHAR (3)    NULL,
    [OWNERID]                               NVARCHAR (18)   NULL,
    [PARTNERACCOUNTID]                      NVARCHAR (18)   NULL,
    [TOTAL_AMOUNT__C]                       DECIMAL (18, 2) NULL,
    [AMOUNT_OF_DATA_GB__C]                  DECIMAL (10)    NULL,
    [ACCOUNT_STATUS__C]                     NVARCHAR (1300) NULL,
    [CONTRACT_EXPIRATION_DATE__C]           DATETIME        NULL,
    [CONTRACTED_DATE__C]                    DATETIME        NULL,
    [CONTRACTED_TERM__C]                    DECIMAL (4)     NULL,
    [ISCONVERTED__C]                        INT             NULL,
    [NAMED_ACCOUNT__C]                      NVARCHAR (1300) NULL,
    [CLOSED_FROM_STAGE__C]                  NVARCHAR (255)  NULL,
    [DOLLARS_PER_GB__C]                     DECIMAL (18, 2) NULL,
    [SALES_REGION__C]                       NVARCHAR (1300) NULL,
    [AMOUNT_WON__C]                         DECIMAL (18, 2) NULL,
    [AMOUNT_LOST__C]                        DECIMAL (18, 2) NULL,
    [COMPETITORS__C]                        NTEXT           NULL,
    [COMMISSION_SPLIT_SALES_PERSON__C]      NVARCHAR (18)   NULL,
    [COMMISSIONABLE_TERRITORY__C]           NVARCHAR (20)   NULL,
    [COMMISSIONABLE_SALES_REGION__C]        NVARCHAR (20)   NULL,
    [APPROVAL_STATUS__C]                    NVARCHAR (255)  NULL,
    [ACCOUNT_CREDIT_STATUS__C]              NVARCHAR (1300) NULL,
    [CONTRACT_END_DATE__C]                  DATETIME        NULL,
    [CONTRACT_START_DATE__C]                DATETIME        NULL,
    [CURRENT_ACTIVE_CONTRACT__C]            NVARCHAR (18)   NULL,
    [NETSUITE_ID__C]                        NVARCHAR (15)   NULL,
    [RENEWAL_TYPE__C]                       NVARCHAR (255)  NULL,
    [COMMISSIONABLE_SALES_TEAM_OVERRIDE__C] INT             NULL,
    [SALES_CONTACT__C]                      NVARCHAR (18)   NULL,
    [TAM__C]                                NVARCHAR (18)   NULL,
    [MKTO_SI__MARKETOANALYZER__C]           NVARCHAR (1300) NULL,
    [NETSUITE_QUOTE__C]                     INT             NULL,
    [E2_OTHER_CONTACT_EMAIL__C]             NVARCHAR (80)   NULL,
    [E2_SHIP_CITY__C]                       NVARCHAR (100)  NULL,
    [E2_SHIP_COMPANY_NAME__C]               NVARCHAR (255)  NULL,
    [E2_SHIP_COUNTRY__C]                    NVARCHAR (100)  NULL,
    [E2_SHIP_STATE__C]                      NVARCHAR (100)  NULL,
    [E2_SHIP_STREET__C]                     NVARCHAR (255)  NULL,
    [E2_SHIP_TO_COMPANY__C]                 NVARCHAR (255)  NULL,
    [E2_SHIP_ZIP__C]                        NVARCHAR (30)   NULL,
    [PORTAL_ORDER_NUMBER__C]                NVARCHAR (20)   NULL,
    [E2_PRODUCT_LINES__C]                   DECIMAL (18)    NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191514342EV_SF_OPPORTUNIT]
    ON [dbo].[EV_SF_OPPORTUNITY]([ID] ASC);

