CREATE TABLE [dbo].[EV_SF_DATED_CURRENCY_RATE__C] (
    [ID]               NVARCHAR (18)  NULL,
    [ISDELETED]        INT            NULL,
    [NAME]             NVARCHAR (38)  NULL,
    [CURRENCYISOCODE]  NVARCHAR (3)   NULL,
    [SETUPOWNERID]     NVARCHAR (18)  NULL,
    [CREATEDDATE]      DATETIME       NULL,
    [CREATEDBYID]      NVARCHAR (18)  NULL,
    [LASTMODIFIEDDATE] DATETIME       NULL,
    [LASTMODIFIEDBYID] NVARCHAR (18)  NULL,
    [SYSTEMMODSTAMP]   DATETIME       NULL,
    [CURRENCY_CODE__C] NVARCHAR (3)   NULL,
    [CURRENCY_NAME__C] NVARCHAR (30)  NULL,
    [END_DATE__C]      DATETIME       NULL,
    [EXCHANGE_RATE__C] DECIMAL (5, 4) NULL,
    [START_DATE__C]    DATETIME       NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191522795EV_SF_DATED_CURR]
    ON [dbo].[EV_SF_DATED_CURRENCY_RATE__C]([ID] ASC);

