CREATE TABLE [dbo].[EV_SF_ACCOUNT_VAULT__C] (
    [ID]                          NVARCHAR (18)   NULL,
    [ISDELETED]                   INT             NULL,
    [NAME]                        NVARCHAR (80)   NULL,
    [CURRENCYISOCODE]             NVARCHAR (3)    NULL,
    [RECORDTYPEID]                NVARCHAR (18)   NULL,
    [CREATEDDATE]                 DATETIME        NULL,
    [CREATEDBYID]                 NVARCHAR (18)   NULL,
    [LASTMODIFIEDDATE]            DATETIME        NULL,
    [LASTMODIFIEDBYID]            NVARCHAR (18)   NULL,
    [SYSTEMMODSTAMP]              DATETIME        NULL,
    [LASTACTIVITYDATE]            DATETIME        NULL,
    [CONNECTIONRECEIVEDID]        NVARCHAR (18)   NULL,
    [CONNECTIONSENTID]            NVARCHAR (18)   NULL,
    [ACCOUNT__C]                  NVARCHAR (18)   NULL,
    [VAULT__C]                    NVARCHAR (18)   NULL,
    [BILLING_CODE__C]             NVARCHAR (45)   NULL,
    [BILLING_TYPE__C]             NVARCHAR (255)  NULL,
    [CREATION_DATE__C]            DATETIME        NULL,
    [CUSTOMER_SHORT_NAME__C]      NVARCHAR (95)   NULL,
    [NOTES__C]                    NTEXT           NULL,
    [SLXID__C]                    NVARCHAR (18)   NULL,
    [STATUS__C]                   NVARCHAR (255)  NULL,
    [VAULT_ACCOUNT_NAME__C]       NVARCHAR (95)   NULL,
    [VAULT_USER_NAME__C]          NVARCHAR (95)   NULL,
    [VAULT_USER_PASSWORD__C]      NVARCHAR (25)   NULL,
    [WEBCC_ACCOUNT_NAME__C]       NVARCHAR (255)  NULL,
    [WEBCC_PASSWORD__C]           NVARCHAR (128)  NULL,
    [WEBCC_URL__C]                NVARCHAR (255)  NULL,
    [WEBCC_USERNAME__C]           NVARCHAR (128)  NULL,
    [VAULT_SHORT_NAME__C]         NVARCHAR (1300) NULL,
    [CONTRACT_ID__C]              NVARCHAR (12)   NULL,
    [OTRK__C]                     NVARCHAR (40)   NULL,
    [EXTERNAL_FQDN__C]            NVARCHAR (1300) NULL,
    [AV_EXTERNAL_ID__C]           NVARCHAR (30)   NULL,
    [VOLUME_TB__C]                DECIMAL (10)    NULL,
    [ERP_BILLING_ID__C]           NVARCHAR (100)  NULL,
    [PRODUCT_ACCOUNT_ID__C]       NVARCHAR (200)  NULL,
    [AZURE_ADDED_EVAULT__C]       INT             NULL,
    [AZURE_DATACENTER__C]         NVARCHAR (255)  NULL,
    [AZURE_SUBSCRIPTION_ID__C]    NVARCHAR (100)  NULL,
    [AZURE_SUBSCRIPTION_NAME__C]  NVARCHAR (100)  NULL,
    [AZURE_VAULTS_QUANTITY__C]    DECIMAL (18)    NULL,
    [ARCHIVE_USERNAME__C]         NVARCHAR (255)  NULL,
    [ARCHIVE_PASSWORD__C]         NVARCHAR (255)  NULL,
    [SMTP_USERNAME__C]            NVARCHAR (255)  NULL,
    [SMTP_PASSWORD__C]            NVARCHAR (255)  NULL,
    [PURCHASED_CAPACITY_GB__C]    DECIMAL (18)    NULL,
    [NUMBER_OF_USERS__C]          DECIMAL (18)    NULL,
    [TOTAL_CONTRACTED_STORAGE__C] DECIMAL (18, 4) NULL,
    [CURRENT_STORAGE_USAGE__C]    DECIMAL (18, 4) NULL,
    [ERA_MONITORING__C]           INT             NULL,
    [UNENCRYPTED_DATA__C]         INT             NULL,
    [UNENCRYPTED_DATA_FLAG__C]    DECIMAL (18, 2) NULL,
    [ASSET__C]                    NVARCHAR (18)   NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191313698EV_SF_ACCOUNT_VA]
    ON [dbo].[EV_SF_ACCOUNT_VAULT__C]([ID] ASC);

