CREATE TABLE [dbo].[EV_SF_TRANSACTION_ITEM__C] (
    [ID]                                        NVARCHAR (18)   NULL,
    [ISDELETED]                                 INT             NULL,
    [NAME]                                      NVARCHAR (80)   NULL,
    [CURRENCYISOCODE]                           NVARCHAR (3)    NULL,
    [RECORDTYPEID]                              NVARCHAR (18)   NULL,
    [CREATEDDATE]                               DATETIME        NULL,
    [CREATEDBYID]                               NVARCHAR (18)   NULL,
    [LASTMODIFIEDDATE]                          DATETIME        NULL,
    [LASTMODIFIEDBYID]                          NVARCHAR (18)   NULL,
    [SYSTEMMODSTAMP]                            DATETIME        NULL,
    [CONNECTIONRECEIVEDID]                      NVARCHAR (18)   NULL,
    [CONNECTIONSENTID]                          NVARCHAR (18)   NULL,
    [TRANSACTION__C]                            NVARCHAR (18)   NULL,
    [AMOUNT__C]                                 DECIMAL (18, 2) NULL,
    [BILLING_ID__C]                             NVARCHAR (80)   NULL,
    [CDR_CERTIFICATION_COMPLETE__C]             INT             NULL,
    [CDR_PROVISIONING_COMPLETE__C]              INT             NULL,
    [CHARGE_TYPE__C]                            NVARCHAR (80)   NULL,
    [CONTRACT_LINE_ITEM__C]                     NVARCHAR (18)   NULL,
    [CREDENTIAL_EMAIL_PROVISIONING_COMPLETE__C] INT             NULL,
    [DATE_PROVISIONED__C]                       DATETIME        NULL,
    [DESCRIPTION__C]                            NTEXT           NULL,
    [DISCOUNT__C]                               DECIMAL (5, 2)  NULL,
    [END_DATE__C]                               DATETIME        NULL,
    [END_USER__C]                               NVARCHAR (18)   NULL,
    [EXPECTED_SHIP_DATE__C]                     DATETIME        NULL,
    [INITIAL_DISCOUNT__C]                       DECIMAL (5, 2)  NULL,
    [ITEM__C]                                   NVARCHAR (18)   NULL,
    [LICENSE_PROVISIONING_COMPLETE__C]          INT             NULL,
    [LINE_ITEM_TAV__C]                          DECIMAL (18, 2) NULL,
    [LINE_ITEM_TCV__C]                          DECIMAL (18, 2) NULL,
    [MANAGED_SERVICES_PROVISIONING_COMPLETE__C] INT             NULL,
    [NETSUITE_ID__C]                            NVARCHAR (15)   NULL,
    [ORDER_LINE_TXN_TYPE__C]                    NVARCHAR (40)   NULL,
    [ORIGINAL_LIST_PRICE__C]                    DECIMAL (18, 2) NULL,
    [PRO_SERVE_PROVISIONING_COMPLETE__C]        INT             NULL,
    [PROCUREMENT_COMPLETE__C]                   INT             NULL,
    [PRODUCT_CODE_SKU__C]                       NVARCHAR (80)   NULL,
    [PRODUCT_TYPE__C]                           NVARCHAR (80)   NULL,
    [QUANTITY__C]                               DECIMAL (10, 1) NULL,
    [SEEDING_DEVICE__C]                         NVARCHAR (255)  NULL,
    [SERVER_ENVIRONMENT__C]                     NVARCHAR (255)  NULL,
    [SERVER_QUANTITY__C]                        DECIMAL (4)     NULL,
    [START_DATE__C]                             DATETIME        NULL,
    [TXM_LINE_UNIQUE_ID__C]                     NVARCHAR (40)   NULL,
    [UNIT_PRICE__C]                             DECIMAL (18, 2) NULL,
    [VAULT_PROVISIONING_COMPLETE__C]            INT             NULL,
    [SYNCH_TO_RELAYWARE__C]                     INT             NULL,
    [TRAINING_PROVISIONING_COMPLETE__C]         INT             NULL,
    [HIDDEN_ADMIN_TEXT_FIELD__C]                NVARCHAR (255)  NULL,
    [LINE_ID__C]                                DECIMAL (18)    NULL,
    [PARENT_LINE_ID__C]                         DECIMAL (18)    NULL,
    [RELAYWARE_ID__C]                           DECIMAL (18)    NULL,
    [SHIPPING_COST__C]                          DECIMAL (10, 2) NULL,
    [SHIPPING_ITEM_DESCRIPTION__C]              NVARCHAR (255)  NULL,
    [SHIPPING_ITEM__C]                          NVARCHAR (18)   NULL,
    [ORIGINAL_NS_INTERNAL_ID__C]                NVARCHAR (15)   NULL,
    [NEW_CARBONITE_NETSUITE_ID__C]              NVARCHAR (15)   NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191630438EV_SF_TRANSACTIO]
    ON [dbo].[EV_SF_TRANSACTION_ITEM__C]([ID] ASC);

