CREATE TABLE [dbo].[EV_SF_TASK] (
    [ID]                              NVARCHAR (18)   NULL,
    [WHOID]                           NVARCHAR (18)   NULL,
    [WHATID]                          NVARCHAR (18)   NULL,
    [SUBJECT]                         NVARCHAR (255)  NULL,
    [ACTIVITYDATE]                    DATETIME        NULL,
    [STATUS]                          NVARCHAR (40)   NULL,
    [PRIORITY]                        NVARCHAR (40)   NULL,
    [ISHIGHPRIORITY]                  INT             NULL,
    [OWNERID]                         NVARCHAR (18)   NULL,
    [DESCRIPTION]                     NTEXT           NULL,
    [CURRENCYISOCODE]                 NVARCHAR (3)    NULL,
    [TYPE]                            NVARCHAR (40)   NULL,
    [ISDELETED]                       INT             NULL,
    [ACCOUNTID]                       NVARCHAR (18)   NULL,
    [ISCLOSED]                        INT             NULL,
    [CREATEDDATE]                     DATETIME        NULL,
    [CREATEDBYID]                     NVARCHAR (18)   NULL,
    [LASTMODIFIEDDATE]                DATETIME        NULL,
    [LASTMODIFIEDBYID]                NVARCHAR (18)   NULL,
    [SYSTEMMODSTAMP]                  DATETIME        NULL,
    [ISARCHIVED]                      INT             NULL,
    [ISVISIBLEINSELFSERVICE]          INT             NULL,
    [CALLDURATIONINSECONDS]           INT             NULL,
    [CALLTYPE]                        NVARCHAR (40)   NULL,
    [CALLDISPOSITION]                 NVARCHAR (255)  NULL,
    [CALLOBJECT]                      NVARCHAR (255)  NULL,
    [REMINDERDATETIME]                DATETIME        NULL,
    [ISREMINDERSET]                   INT             NULL,
    [CONNECTIONRECEIVEDID]            NVARCHAR (18)   NULL,
    [CONNECTIONSENTID]                NVARCHAR (18)   NULL,
    [RECURRENCEACTIVITYID]            NVARCHAR (18)   NULL,
    [ISRECURRENCE]                    INT             NULL,
    [RECURRENCESTARTDATEONLY]         DATETIME        NULL,
    [RECURRENCEENDDATEONLY]           DATETIME        NULL,
    [RECURRENCETIMEZONESIDKEY]        NVARCHAR (40)   NULL,
    [RECURRENCETYPE]                  NVARCHAR (40)   NULL,
    [RECURRENCEINTERVAL]              INT             NULL,
    [RECURRENCEDAYOFWEEKMASK]         INT             NULL,
    [RECURRENCEDAYOFMONTH]            INT             NULL,
    [RECURRENCEINSTANCE]              NVARCHAR (40)   NULL,
    [RECURRENCEMONTHOFYEAR]           NVARCHAR (40)   NULL,
    [RECURRENCEREGENERATEDTYPE]       NVARCHAR (40)   NULL,
    [CATEGORY__C]                     NVARCHAR (64)   NULL,
    [SLXID__C]                        NVARCHAR (18)   NULL,
    [QBDIALER__CALL_DATE_TIME__C]     DATETIME        NULL,
    [QBDIALER__CALLBACK_DATE_TIME__C] DATETIME        NULL,
    [QBDIALER__IMPRESSIONID__C]       DECIMAL (18)    NULL,
    [QBDIALER__CALLRECORDINGURL__C]   NVARCHAR (255)  NULL,
    [CREATED_BY_ROLE__C]              NVARCHAR (1300) NULL,
    [I__EMAILHASATTACHMENTS__C]       INT             NULL,
    [I__EMAILID__C]                   NVARCHAR (18)   NULL,
    [QBDIALER__CALL_DIAL_NUMBER__C]   DECIMAL (18)    NULL,
    [QBDIALER__CALL_HOUR__C]          NVARCHAR (8)    NULL,
    [QBDIALER__CALL_LEAD_STATUS__C]   NVARCHAR (40)   NULL,
    [QBDIALER__CALL_RING_TIME__C]     DECIMAL (18)    NULL,
    [QBDIALER__CALL_TIME_ZONE__C]     NVARCHAR (20)   NULL,
    [FILECT__C]                       DECIMAL (8)     NULL,
    [IHANCEID__C]                     NVARCHAR (32)   NULL,
    [PAGECT__C]                       DECIMAL (8)     NULL,
    [RADIALCA__POST_TO_CHATTER__C]    INT             NULL,
    [CREATED_DATE_TIME__C]            DATETIME        NULL,
    [QBDIALER__SMSREMINDER__C]        INT             NULL,
    [I__EMAIL__C]                     NVARCHAR (18)   NULL,
    [HIDDEN_ADMIN_TEXT_FIELD__C]      NVARCHAR (128)  NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191532343EV_SF_TASK_ID]
    ON [dbo].[EV_SF_TASK]([ID] ASC);

