CREATE TABLE [dbo].[EV_SF_VAULT__C] (
    [ID]                                      NVARCHAR (18)   NULL,
    [OWNERID]                                 NVARCHAR (18)   NULL,
    [ISDELETED]                               INT             NULL,
    [NAME]                                    NVARCHAR (80)   NULL,
    [CURRENCYISOCODE]                         NVARCHAR (3)    NULL,
    [RECORDTYPEID]                            NVARCHAR (18)   NULL,
    [CREATEDDATE]                             DATETIME        NULL,
    [CREATEDBYID]                             NVARCHAR (18)   NULL,
    [LASTMODIFIEDDATE]                        DATETIME        NULL,
    [LASTMODIFIEDBYID]                        NVARCHAR (18)   NULL,
    [SYSTEMMODSTAMP]                          DATETIME        NULL,
    [LASTACTIVITYDATE]                        DATETIME        NULL,
    [LASTVIEWEDDATE]                          DATETIME        NULL,
    [LASTREFERENCEDDATE]                      DATETIME        NULL,
    [CONNECTIONRECEIVEDID]                    NVARCHAR (18)   NULL,
    [CONNECTIONSENTID]                        NVARCHAR (18)   NULL,
    [CO_LOCATION_STATUS__C]                   NVARCHAR (1300) NULL,
    [CO_LOCATION__C]                          NVARCHAR (18)   NULL,
    [DIRECTOR_VERSION__C]                     NVARCHAR (255)  NULL,
    [EVREPORTS_URL__C]                        NVARCHAR (160)  NULL,
    [EXTERNAL_FQDN__C]                        NVARCHAR (255)  NULL,
    [EXTERNAL_IP_ADDRESS__C]                  NVARCHAR (128)  NULL,
    [HOSTNAME__C]                             NVARCHAR (255)  NULL,
    [INTERNAL_FQDN__C]                        NVARCHAR (255)  NULL,
    [INTERNAL_IP_ADDRESS__C]                  NVARCHAR (25)   NULL,
    [ITEM_TYPE__C]                            NVARCHAR (40)   NULL,
    [LINK_VITAL_STATISTIC_CACTI__C]           NVARCHAR (255)  NULL,
    [LINK_VITAL_STATISTIC_NAGIOS__C]          NVARCHAR (255)  NULL,
    [NOTES__C]                                NVARCHAR (255)  NULL,
    [OS_SERVICE_PACK__C]                      NVARCHAR (255)  NULL,
    [PATH__C]                                 NVARCHAR (80)   NULL,
    [ROLE__C]                                 NVARCHAR (255)  NULL,
    [STORAGE_TYPE__C]                         NVARCHAR (255)  NULL,
    [SUBTYPE__C]                              NVARCHAR (255)  NULL,
    [TOTAL_STORAGE_CAPACITY__C]               NVARCHAR (128)  NULL,
    [TYPE__C]                                 NVARCHAR (255)  NULL,
    [TYPE_OF_SERVICE__C]                      NVARCHAR (255)  NULL,
    [VAULT_ADMIN__C]                          NVARCHAR (18)   NULL,
    [VAULT_LEGACY_NAME__C]                    NVARCHAR (40)   NULL,
    [VAULT_STATUS__C]                         NVARCHAR (255)  NULL,
    [VAULT_NAME_DEDUPE_CHECK__C]              NVARCHAR (255)  NULL,
    [GUID__C]                                 NVARCHAR (255)  NULL,
    [BILLING_TYPE__C]                         NVARCHAR (255)  NULL,
    [SPLUNK_D__C]                             NVARCHAR (255)  NULL,
    [SPLUNK_EMAIL__C]                         NVARCHAR (80)   NULL,
    [REPLICATING__C]                          NVARCHAR (255)  NULL,
    [DISTRIBUTOR__C]                          NVARCHAR (18)   NULL,
    [DATA_DELETION_ENABLED__C]                INT             NULL,
    [BAV__C]                                  NVARCHAR (18)   NULL,
    [REMOTE_MONITORING__C]                    NVARCHAR (255)  NULL,
    [REMOTE_MONITORING_URL__C]                NVARCHAR (255)  NULL,
    [OWNER_ROLE__C]                           NVARCHAR (1300) NULL,
    [REFUSED_MONITORING__C]                   NVARCHAR (18)   NULL,
    [IPSEC_ADDRESS__C]                        NVARCHAR (25)   NULL,
    [EMERGENCY_CONTACT_S__C]                  NVARCHAR (255)  NULL,
    [RDP_ADDRESS__C]                          NVARCHAR (160)  NULL,
    [OMIT_TASK_ESRSE__C]                      NTEXT           NULL,
    [OMIT_TASK_FBR__C]                        NTEXT           NULL,
    [REPORT_NOTES__C]                         NTEXT           NULL,
    [VPN_URL__C]                              NVARCHAR (160)  NULL,
    [HARDWARE_OWNER__C]                       NVARCHAR (255)  NULL,
    [VAULT_IS_FULL_OR_AT_STORAGE_CAPACITY__C] INT             NULL,
    [PORTAL_UI__C]                            INT             NULL,
    [CLOUD_SERVICE_NAME__C]                   NVARCHAR (255)  NULL,
    [WEBCC__C]                                INT             NULL,
    [EV_REPORTS__C]                           INT             NULL,
    [PROXY__C]                                INT             NULL,
    [DATABASE__C]                             INT             NULL,
    [AGENT_INSTALLER__C]                      INT             NULL,
    [AMPPROXYSERVICE__C]                      INT             NULL,
    [AMPREDIRECTORSERVICE__C]                 INT             NULL,
    [PROPAGATIONSERVICE__C]                   INT             NULL,
    [MSSQLSERVER__C]                          INT             NULL,
    [ERLOGIN__C]                              INT             NULL,
    [LOADER__C]                               INT             NULL,
    [REPORTMANAGER__C]                        INT             NULL,
    [REPORTVIEWER__C]                         INT             NULL,
    [TOKENMANAGER__C]                         INT             NULL,
    [HOST_PROTECT__C]                         INT             NULL,
    [NOTIFICATION__C]                         INT             NULL,
    [PORTAL_SERVICE_CONNECTOR__C]             INT             NULL,
    [REGISTRATION__C]                         INT             NULL,
    [BACKUPCONSOLE__C]                        INT             NULL,
    [LOGIN__C]                                INT             NULL,
    [CDR__C]                                  INT             NULL,
    [MS__C]                                   INT             NULL,
    [VAULT_PARTNER__C]                        NVARCHAR (255)  NULL,
    [AD_RECORD__C]                            NVARCHAR (18)   NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191756579EV_SF_VAULT__C_I]
    ON [dbo].[EV_SF_VAULT__C]([ID] ASC);

