CREATE TABLE [dbo].[EV_SF_ACCOUNT] (
    [ID]                                          NVARCHAR (18)    NULL,
    [ISDELETED]                                   INT              NULL,
    [MASTERRECORDID]                              NVARCHAR (18)    NULL,
    [NAME]                                        NVARCHAR (255)   NULL,
    [TYPE]                                        NVARCHAR (40)    NULL,
    [RECORDTYPEID]                                NVARCHAR (18)    NULL,
    [PARENTID]                                    NVARCHAR (18)    NULL,
    [BILLINGSTREET]                               NVARCHAR (255)   NULL,
    [BILLINGCITY]                                 NVARCHAR (40)    NULL,
    [BILLINGSTATE]                                NVARCHAR (80)    NULL,
    [BILLINGPOSTALCODE]                           NVARCHAR (20)    NULL,
    [BILLINGCOUNTRY]                              NVARCHAR (80)    NULL,
    [BILLINGLATITUDE]                             DECIMAL (18, 15) NULL,
    [BILLINGLONGITUDE]                            DECIMAL (18, 15) NULL,
    [SHIPPINGSTREET]                              NVARCHAR (255)   NULL,
    [SHIPPINGCITY]                                NVARCHAR (40)    NULL,
    [SHIPPINGSTATE]                               NVARCHAR (80)    NULL,
    [SHIPPINGPOSTALCODE]                          NVARCHAR (20)    NULL,
    [SHIPPINGCOUNTRY]                             NVARCHAR (80)    NULL,
    [SHIPPINGLATITUDE]                            DECIMAL (18, 15) NULL,
    [SHIPPINGLONGITUDE]                           DECIMAL (18, 15) NULL,
    [PHONE]                                       NVARCHAR (40)    NULL,
    [FAX]                                         NVARCHAR (40)    NULL,
    [ACCOUNTNUMBER]                               NVARCHAR (40)    NULL,
    [WEBSITE]                                     NVARCHAR (255)   NULL,
    [PHOTOURL]                                    NVARCHAR (255)   NULL,
    [SIC]                                         NVARCHAR (20)    NULL,
    [INDUSTRY]                                    NVARCHAR (40)    NULL,
    [ANNUALREVENUE]                               DECIMAL (18)     NULL,
    [NUMBEROFEMPLOYEES]                           INT              NULL,
    [OWNERSHIP]                                   NVARCHAR (40)    NULL,
    [TICKERSYMBOL]                                NVARCHAR (20)    NULL,
    [DESCRIPTION]                                 NTEXT            NULL,
    [RATING]                                      NVARCHAR (40)    NULL,
    [SITE]                                        NVARCHAR (80)    NULL,
    [CURRENCYISOCODE]                             NVARCHAR (3)     NULL,
    [OWNERID]                                     NVARCHAR (18)    NULL,
    [CREATEDDATE]                                 DATETIME         NULL,
    [CREATEDBYID]                                 NVARCHAR (18)    NULL,
    [LASTMODIFIEDDATE]                            DATETIME         NULL,
    [LASTMODIFIEDBYID]                            NVARCHAR (18)    NULL,
    [SYSTEMMODSTAMP]                              DATETIME         NULL,
    [LASTACTIVITYDATE]                            DATETIME         NULL,
    [LASTVIEWEDDATE]                              DATETIME         NULL,
    [LASTREFERENCEDDATE]                          DATETIME         NULL,
    [ISPARTNER]                                   INT              NULL,
    [ISCUSTOMERPORTAL]                            INT              NULL,
    [JIGSAW]                                      NVARCHAR (20)    NULL,
    [JIGSAWCOMPANYID]                             NVARCHAR (20)    NULL,
    [ACCOUNTSOURCE]                               NVARCHAR (40)    NULL,
    [SICDESC]                                     NVARCHAR (80)    NULL,
    [CONNECTIONRECEIVEDID]                        NVARCHAR (18)    NULL,
    [CONNECTIONSENTID]                            NVARCHAR (18)    NULL,
    [SLXID__C]                                    NVARCHAR (25)    NULL,
    [ACCOUNT_STATUS__C]                           NVARCHAR (255)   NULL,
    [PARTNER_TYPE__C]                             NVARCHAR (255)   NULL,
    [ORIGINAL_OWNER__C]                           NVARCHAR (40)    NULL,
    [ACCOUNT_EMAIL__C]                            NVARCHAR (50)    NULL,
    [CONTRACT_DATE__C]                            DATETIME         NULL,
    [NON_PROFIT__C]                               INT              NULL,
    [ACCOUNTID__C]                                NVARCHAR (1300)  NULL,
    [CHANNEL_PARTNER__C]                          NTEXT            NULL,
    [PRIORITY_ACCOUNT__C]                         INT              NULL,
    [ART_POTENTIAL_PARTNER_TYPE__C]               NVARCHAR (100)   NULL,
    [BRANDED_CUSTOMER__C]                         NVARCHAR (255)   NULL,
    [CONTRACT_CANCELLATION_STATUS__C]             NVARCHAR (255)   NULL,
    [CONTRACT_STATUS__C]                          NVARCHAR (255)   NULL,
    [DONOTSOLICIT__C]                             INT              NULL,
    [GP_ID__C]                                    NVARCHAR (30)    NULL,
    [IMPORT_SOURCE__C]                            NVARCHAR (255)   NULL,
    [LRT_ART__C]                                  NVARCHAR (100)   NULL,
    [DAYS_IN_PARTNER_PROGRAM__C]                  DECIMAL (18)     NULL,
    [MAS_ACCTID__C]                               NVARCHAR (128)   NULL,
    [NAMED_ACCOUNT__C]                            INT              NULL,
    [INDUSTRY_SPECIALIZATION__C]                  NTEXT            NULL,
    [PRODUCT_INTEREST__C]                         NTEXT            NULL,
    [SUBTYPE__C]                                  NVARCHAR (255)   NULL,
    [VAT_NUMBER__C]                               NVARCHAR (50)    NULL,
    [VERTICAL_TYPE__C]                            NVARCHAR (255)   NULL,
    [SALES_REGION__C]                             NVARCHAR (255)   NULL,
    [TERRITORY__C]                                NVARCHAR (255)   NULL,
    [DO_NOT_DELETE_DATA__C]                       INT              NULL,
    [QBDIALER__DIALS__C]                          DECIMAL (18)     NULL,
    [QBDIALER__LASTCALLTIME__C]                   DATETIME         NULL,
    [QBDIALER__RESPONSETIME__C]                   DECIMAL (18)     NULL,
    [HAS_ASSETS__C]                               INT              NULL,
    [HIDDEN_LEGITIMATE_DUPE__C]                   INT              NULL,
    [PARTNER_SPECIALIZATION_CCSP__C]              DECIMAL (18)     NULL,
    [PARTNER_SPECIALIZATION_EDPM__C]              DECIMAL (18)     NULL,
    [PARTNER_SPECIALIZATION_SW_HW__C]             DECIMAL (18)     NULL,
    [PARTNER_SPECIALIZATION_SAAS__C]              DECIMAL (18)     NULL,
    [COMMISSION_DISTRICT_OVERRIDE_APPROVAL__C]    DATETIME         NULL,
    [PARTNER_ACCOUNT_ID__C]                       NVARCHAR (20)    NULL,
    [TOP_HIERARCHY_NAME__C]                       NVARCHAR (1300)  NULL,
    [TOP_HIERARCHY_ID__C]                         NVARCHAR (1300)  NULL,
    [TERRITORY_TAM__C]                            NVARCHAR (255)   NULL,
    [RDR_SERVER_COUNT__C]                         DECIMAL (18)     NULL,
    [NAICS_CODE__C]                               NVARCHAR (255)   NULL,
    [ENTITY_TYPE__C]                              NVARCHAR (255)   NULL,
    [ACCOUNT_CREATION_VALIDATION__C]              INT              NULL,
    [ALLIANCE_TARGET_ACCOUNT__C]                  INT              NULL,
    [OWNERSHIP_EXCEPTION__C]                      INT              NULL,
    [PARTNER_PROGRAM_DATE__C]                     DATETIME         NULL,
    [MANAGED_PARTNER__C]                          INT              NULL,
    [PARTNER_TICKET_SHARING__C]                   INT              NULL,
    [CUSTOMIZED_CONTRACT_APPROVED_BY__C]          NVARCHAR (255)   NULL,
    [CUSTOMIZED_CONTRACT_APPROVED_DATE__C]        DATETIME         NULL,
    [CUSTOMIZED_CONTRACT__C]                      NVARCHAR (255)   NULL,
    [LIST_ON_PARTNER_FINDER__C]                   NVARCHAR (255)   NULL,
    [PARTNER_ONBOARDING_INFORMATION_COMPLETED__C] INT              NULL,
    [TAX_EXEMPT__C]                               NVARCHAR (255)   NULL,
    [TAX_EXEMPTION_APPROVED__C]                   DATETIME         NULL,
    [BUSINESS_PLAN_COMPLETED__C]                  INT              NULL,
    [DATE_BUSINESS_PLAN_COMPLETED__C]             DATETIME         NULL,
    [PARTNER_ENABLEMENT_MARKETING_COMPLETED__C]   NTEXT            NULL,
    [PARTNER_ENABLEMENT_MARKETING_TO_DO__C]       NVARCHAR (1300)  NULL,
    [PARTNER_ENABLEMENT_SALES_COMPLETED__C]       NTEXT            NULL,
    [PARTNER_ENABLEMENT_SALES_TO_DO__C]           NVARCHAR (1300)  NULL,
    [DISTRICT_OVERRIDE_COUNTRY__C]                NVARCHAR (255)   NULL,
    [DISTRICT_OVERRIDE_ZIP_CODE__C]               NVARCHAR (20)    NULL,
    [GEO__C]                                      NVARCHAR (1300)  NULL,
    [SYNNEX_ACCOUNT_STATUS__C]                    NVARCHAR (255)   NULL,
    [SAAS_SUPPORT_STATUS__C]                      NVARCHAR (255)   NULL,
    [ACCOUNT_MAPPING_SESSIONS_COMPLETED__C]       DATETIME         NULL,
    [CO_BRANDING_COMPLETED__C]                    DATETIME         NULL,
    [GO_TO_MARKET_PLAN_COMPLETED__C]              DATETIME         NULL,
    [FIRST_DEAL_EVANAGELIZED__C]                  DATETIME         NULL,
    [FIRST_DEMANDGEN_EVENTCAMPAIGN_COMPLETED__C]  DATETIME         NULL,
    [FIRST_TWO_DEALS_COMPLETED__C]                DATETIME         NULL,
    [JOINT_PR_SOCIAL_MEDIA_STRATEGY_COMPLETED__C] DATETIME         NULL,
    [JOINT_SALES_CALLS_COMPLETED__C]              DATETIME         NULL,
    [NFR_REQUESTS_REVIEWED__C]                    DATETIME         NULL,
    [PARTNER_RECEIVES_LEADS__C]                   DATETIME         NULL,
    [PIPELINE_METRICS_DEFINED__C]                 DATETIME         NULL,
    [SOLUTION_ARCHITECT_REP__C]                   NVARCHAR (18)    NULL,
    [TWO_JOINT_INSTALLATIONS_COMPLETED__C]        DATETIME         NULL,
    [MARKETING_ENABLEMENT_INITIATED__C]           DATETIME         NULL,
    [SALES_ENABLEMENT_COMPLETED__C]               DATETIME         NULL,
    [MARKETING_ENABLEMENT_COMPLETED__C]           DATETIME         NULL,
    [SALES_ENABLEMENT_INITIATED__C]               DATETIME         NULL,
    [DAYS_TO_COMPLETE_BUSINESS_PLAN__C]           DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_SALES_ENABLEMENT__C]        DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_NFR_REQUESTS__C]            DECIMAL (18)     NULL,
    [VERTICAL_ORG_MANUAL_OVERRIDE__C]             INT              NULL,
    [DAYS_TO_COMPLETE_PIPELINE_METRICS__C]        DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_ACCOUNT_MAPPING__C]         DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_JOINT_SALES_CALLS__C]       DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_FIRST_TWO_DEALS__C]         DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_FIRST_DEAL_EVANGELIZED__C]  DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_FIRST_TWO_INSTALLATIONS__C] DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_MARKETING_ENABLEMENT__C]    DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_FIRST_DEMANDGEN_EVENT__C]   DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_CO_BRANDING__C]             DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_GO_TO_MARKET_PLAN__C]       DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_PARTNER_LEAD_SETUP__C]      DECIMAL (18)     NULL,
    [DAYS_TO_COMPLETE_JOINT_PR_STRATEGY__C]       DECIMAL (18)     NULL,
    [COMMISSION_DISTRICT_OVERRIDE__C]             NVARCHAR (255)   NULL,
    [COMMISSIONABLE_DISTRICT__C]                  NVARCHAR (50)    NULL,
    [COMMISSIONABLE_TERRITORY__C]                 NVARCHAR (20)    NULL,
    [COMMISSIONABLE_SALES_REGION__C]              NVARCHAR (20)    NULL,
    [CUSTOMER_SUPPORT_SPECIAL_CONSIDERATIONS__C]  NTEXT            NULL,
    [AGREE_TO_SAAS_FREEMIUM_TERMS__C]             INT              NULL,
    [CREDIT_HOLD__C]                              INT              NULL,
    [CANCELLATION_DATE__C]                        DATETIME         NULL,
    [SE_CERTIFICATION__C]                         DATETIME         NULL,
    [CONTACTS_SE_CERTIFIED__C]                    DECIMAL (18)     NULL,
    [CONTACTS_SALES_CERTIFIED__C]                 DECIMAL (18)     NULL,
    [SALES_CERTIFICATION__C]                      DATETIME         NULL,
    [CONTACTS_INSTALLATION_CERTIFIED__C]          DECIMAL (18)     NULL,
    [INSTALLATION_CERTIFICATION__C]               DATETIME         NULL,
    [CONTACTS_EV_I_COMPLETED__C]                  DECIMAL (18)     NULL,
    [EV_I_TRAINING__C]                            DATETIME         NULL,
    [CONTACTS_EV_II_COMPLETED__C]                 DECIMAL (18)     NULL,
    [EV_II_TRAINING__C]                           DATETIME         NULL,
    [CONTACTS_PASSED_ECTS_ASSESSMENT__C]          DECIMAL (18)     NULL,
    [PARTNER_STATUS__C]                           NVARCHAR (255)   NULL,
    [REVENUE_PROJECTION_CO_SIGNED__C]             DECIMAL (8, 2)   NULL,
    [CDR_REP__C]                                  NVARCHAR (18)    NULL,
    [VERTICAL_ORG__C]                             NVARCHAR (255)   NULL,
    [LAST_ACCOUNT_PROFILE_UPDATE__C]              DATETIME         NULL,
    [INSIDEVIEW_ID__C]                            NVARCHAR (18)    NULL,
    [MARKETING_ENABLEMENT_COMPLETED_FORMULA__C]   DATETIME         NULL,
    [SALES_ENABLEMENT_COMPLETED_FORMULA__C]       DATETIME         NULL,
    [OWNER_SALES_ORG__C]                          NVARCHAR (1300)  NULL,
    [LOGO_ON_WEBSITE__C]                          INT              NULL,
    [DISPLAY_STATUS__C]                           NVARCHAR (1300)  NULL,
    [PARTNER_PORTAL_APPROVED__C]                  INT              NULL,
    [PARTNER_PORTAL_ACCESS__C]                    NVARCHAR (255)   NULL,
    [YEARS_IN_BUSINESS__C]                        DECIMAL (18)     NULL,
    [OF_CLIENTS__C]                               DECIMAL (18)     NULL,
    [OF_LOCATIONS__C]                             DECIMAL (18)     NULL,
    [OF_MARKETING_PEOPLE__C]                      DECIMAL (18)     NULL,
    [OF_SALES_ENGINEERS__C]                       DECIMAL (18)     NULL,
    [OF_SALES_PEOPLE__C]                          DECIMAL (18)     NULL,
    [PORTAL_LANGUAGE__C]                          NVARCHAR (255)   NULL,
    [ACTIVE_BUSINESS_PLAN_VALIDATION__C]          DECIMAL (18)     NULL,
    [RELAYWARE_ID__C]                             DECIMAL (18)     NULL,
    [OVERRIDE_PORTAL_ACCESS_APPROVAL__C]          INT              NULL,
    [OVERRIDE_PORTAL_ACCESS_USER__C]              NVARCHAR (255)   NULL,
    [HIDDEN_CONVERTED_LEAD_ID__C]                 NVARCHAR (18)    NULL,
    [COMPANY_EMAIL__C]                            NVARCHAR (80)    NULL,
    [PARTNER_SUB_TYPE__C]                         NTEXT            NULL,
    [PARTNER_TERRITORY_FOCUS__C]                  NVARCHAR (255)   NULL,
    [BRANDING__C]                                 NVARCHAR (255)   NULL,
    [PRODUCTS_IN_PARTNER_PORTFOLIO__C]            NVARCHAR (255)   NULL,
    [ONBOARDING_INFORMATION__C]                   NTEXT            NULL,
    [PARTNER_CENTER_REGISTRATION__C]              DATETIME         NULL,
    [DEAL_REGISTRATION_TRAINING__C]               DATETIME         NULL,
    [SOLUTIONS_SHOWCASE_REGISTRATION__C]          DATETIME         NULL,
    [I__DAYSSINCELASTMAIL__C]                     DECIMAL (18)     NULL,
    [I__LASTINBOUNDMAIL__C]                       NVARCHAR (18)    NULL,
    [I__LASTINBOUNDSENT__C]                       DATETIME         NULL,
    [I__LASTINBOUNDTIME__C]                       DATETIME         NULL,
    [I__LASTMAILSENT__C]                          DATETIME         NULL,
    [I__LASTMAILTIMEDELTA__C]                     DECIMAL (18)     NULL,
    [I__LASTMAILTIME__C]                          DATETIME         NULL,
    [I__LASTMAIL__C]                              NVARCHAR (18)    NULL,
    [I__LASTOUTBOUNDMAIL__C]                      NVARCHAR (18)    NULL,
    [I__LASTOUTBOUNDSENT__C]                      DATETIME         NULL,
    [I__LASTOUTBOUNDTIME__C]                      DATETIME         NULL,
    [NATIONWIDE_COVERAGE__C]                      INT              NULL,
    [FORTUNE_RANKING__C]                          NVARCHAR (4)     NULL,
    [FISCAL_YEAR_END__C]                          NVARCHAR (2)     NULL,
    [CREDIT_STATUS__C]                            NVARCHAR (255)   NULL,
    [CUSTOMER_ID__C]                              NVARCHAR (15)    NULL,
    [CUSTOMER_TYPE__C]                            NVARCHAR (100)   NULL,
    [CUSTOMER_TYPE_FROM_NS__C]                    NVARCHAR (30)    NULL,
    [DIVISION__C]                                 NVARCHAR (255)   NULL,
    [FINANCE_APPROVED_DATE__C]                    DATETIME         NULL,
    [INTEGRATION_ERROR__C]                        NVARCHAR (255)   NULL,
    [IS_SYNNEX__C]                                INT              NULL,
    [KEEP__C]                                     INT              NULL,
    [MANAGED_SERVICES_STATUS__C]                  NVARCHAR (255)   NULL,
    [NS_CUSTOMER_TYPE__C]                         NVARCHAR (1300)  NULL,
    [NETSUITE_ID__C]                              NVARCHAR (10)    NULL,
    [PO_REQUIRED_FOR_ORDER__C]                    INT              NULL,
    [SUBSIDIARY__C]                               NVARCHAR (255)   NULL,
    [TERMS__C]                                    NVARCHAR (255)   NULL,
    [LATEST_OPPORTUNITY_CREATE_DATE__C]           DATETIME         NULL,
    [PERFORM_CREDIT_CHECK__C]                     INT              NULL,
    [REFERENCE_AGREEMENT__C]                      INT              NULL,
    [REFERENCE_TYPE__C]                           NTEXT            NULL,
    [NETSUITE_CUSTOMER_NUMBER__C]                 NVARCHAR (20)    NULL,
    [PARTNER_PORTAL_OVERVIEW_COMPLETE__C]         INT              NULL,
    [SSL_VPN_CONNECTIONS__C]                      DECIMAL (18)     NULL,
    [VPN_TUNNEL__C]                               DECIMAL (18)     NULL,
    [LEAD_GEO__C]                                 NVARCHAR (255)   NULL,
    [MANUALLY_PUSHED_TO_NS__C]                    INT              NULL,
    [CURRENT_STORAGE_USAGE__C]                    DECIMAL (18, 4)  NULL,
    [TOTAL_CONTRACTED_STORAGE__C]                 DECIMAL (18, 4)  NULL,
    [ORIGINAL_NS_INTERNAL_ID__C]                  NVARCHAR (8)     NULL,
    [SEAGATE_CUSTOMER__C]                         INT              NULL,
    [MANAGED_BY_DISTRIBUTOR__C]                   INT              NULL,
    [SAP_ACCOUNT_GROUP__C]                        NVARCHAR (255)   NULL,
    [SAP_CREDIT_LIMIT__C]                         DECIMAL (17)     NULL,
    [SAP_CUSTOMERNUM_NAME__C]                     NVARCHAR (200)   NULL,
    [SAP_CUSTOMER_GROUP__C]                       NVARCHAR (50)    NULL,
    [SAP_CUSTOMER_ID__C]                          NVARCHAR (18)    NULL,
    [SAP_IDOC_RCVD__C]                            INT              NULL,
    [SAP_LANGUAGE_CODE__C]                        NVARCHAR (2)     NULL,
    [SAP_REGION_CODE__C]                          NVARCHAR (50)    NULL,
    [SAP_RISK_CATEGORY__C]                        NVARCHAR (200)   NULL,
    [SAP_SUB_REGION__C]                           NVARCHAR (50)    NULL,
    [SAP_TIER__C]                                 NVARCHAR (5)     NULL,
    [SHIPPINGCOUNTRYCODE__C]                      NVARCHAR (3)     NULL,
    [SAP_DIVISION__C]                             NVARCHAR (3)     NULL,
    [QBDIALER__TIMEZONESIDKEY__C]                 NVARCHAR (24)    NULL,
    [CARBONITE_CUSTOMER__C]                       INT              NULL,
    [COMPANY_ID__C]                               NVARCHAR (30)    NULL,
    [CREDIT_CARD_CUSTOMER__C]                     INT              NULL,
    [NETP_SPX__COMPANY_INDUSTRIES__C]             NTEXT            NULL,
    [NETP_SPX__NETPROSPEX_ID__C]                  NVARCHAR (255)   NULL,
    [NETP_SPX__NUMBEROFEMPLOYEES__C]              DECIMAL (8)      NULL,
    [NETP_SPX__SICCODE__C]                        NVARCHAR (15)    NULL,
    [NETP_SPX__SIC_CODES__C]                      NTEXT            NULL,
    [NETP_SPX__SIC_DESCRIPTION__C]                NVARCHAR (255)   NULL,
    [NETP_SPX__WEBSITE__C]                        NVARCHAR (255)   NULL,
    [CRITICAL_WATCH_LIST__C]                      INT              NULL,
    [UNENCRYPTED_DATA_COUNT__C]                   DECIMAL (18, 2)  NULL,
    [US_CITIZEN_REQUIRED__C]                      INT              NULL,
    [PARTNER_LEVEL__C]                            NVARCHAR (255)   NULL,
    [LTS2_ID__C]                                  NVARCHAR (32)    NULL,
    [CUSTOMER_PARTNER_LEVEL__C]                   NVARCHAR (255)   NULL,
    [EXTERNAL_FUL2_ID__C]                         NVARCHAR (18)    NULL,
    [GREAT_PLAINS_ID__C]                          NVARCHAR (28)    NULL,
    [CARBONITE_UID__C]                            NVARCHAR (20)    NULL,
    [MSP_CONTRACT_STATUS__C]                      NVARCHAR (255)   NULL,
    [NS_RESELLER__C]                              INT              NULL,
    [NETSUITE_CUSTOMER__C]                        NVARCHAR (1300)  NULL,
    [PORTAL_COMPANY_ID_CREATED__C]                INT              NULL,
    [PORTAL_PASSWORD__C]                          NVARCHAR (50)    NULL,
    [PORTAL_USER_NAME__C]                         NVARCHAR (255)   NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609161918903EV_SF_ACCOUNT_ID]
    ON [dbo].[EV_SF_ACCOUNT]([ID] ASC);

