CREATE TABLE [dbo].[EV_SF_CASE] (
    [ID]                                         NVARCHAR (18)   NULL,
    [ISDELETED]                                  INT             NULL,
    [CASENUMBER]                                 NVARCHAR (30)   NULL,
    [CONTACTID]                                  NVARCHAR (18)   NULL,
    [ACCOUNTID]                                  NVARCHAR (18)   NULL,
    [PARENTID]                                   NVARCHAR (18)   NULL,
    [SUPPLIEDNAME]                               NVARCHAR (80)   NULL,
    [SUPPLIEDEMAIL]                              NVARCHAR (80)   NULL,
    [SUPPLIEDPHONE]                              NVARCHAR (40)   NULL,
    [SUPPLIEDCOMPANY]                            NVARCHAR (80)   NULL,
    [TYPE]                                       NVARCHAR (40)   NULL,
    [RECORDTYPEID]                               NVARCHAR (18)   NULL,
    [STATUS]                                     NVARCHAR (40)   NULL,
    [REASON]                                     NVARCHAR (40)   NULL,
    [ORIGIN]                                     NVARCHAR (40)   NULL,
    [ISVISIBLEINSELFSERVICE]                     INT             NULL,
    [SUBJECT]                                    NVARCHAR (255)  NULL,
    [PRIORITY]                                   NVARCHAR (40)   NULL,
    [DESCRIPTION]                                NTEXT           NULL,
    [ISCLOSED]                                   INT             NULL,
    [CLOSEDDATE]                                 DATETIME        NULL,
    [ISESCALATED]                                INT             NULL,
    [HASCOMMENTSUNREADBYOWNER]                   INT             NULL,
    [HASSELFSERVICECOMMENTS]                     INT             NULL,
    [CURRENCYISOCODE]                            NVARCHAR (3)    NULL,
    [OWNERID]                                    NVARCHAR (18)   NULL,
    [CREATEDDATE]                                DATETIME        NULL,
    [CREATEDBYID]                                NVARCHAR (18)   NULL,
    [LASTMODIFIEDDATE]                           DATETIME        NULL,
    [LASTMODIFIEDBYID]                           NVARCHAR (18)   NULL,
    [SYSTEMMODSTAMP]                             DATETIME        NULL,
    [LASTVIEWEDDATE]                             DATETIME        NULL,
    [LASTREFERENCEDDATE]                         DATETIME        NULL,
    [CONNECTIONRECEIVEDID]                       NVARCHAR (18)   NULL,
    [CONNECTIONSENTID]                           NVARCHAR (18)   NULL,
    [DESIRED_START_DATE__C]                      DATETIME        NULL,
    [LAST_TOUCH_DAYS__C]                         DECIMAL (18)    NULL,
    [CONTRACT_STATUS__C]                         NVARCHAR (1300) NULL,
    [DO_NOT_DELETE_DATA__C]                      NVARCHAR (1300) NULL,
    [VAULT_NAME__C]                              NVARCHAR (1300) NULL,
    [BILLABLE_HOURS__C]                          DECIMAL (8, 2)  NULL,
    [BILLABLE_RATE__C]                           DECIMAL (18, 2) NULL,
    [NON_BILLABLE_HOURS__C]                      DECIMAL (8, 2)  NULL,
    [PS_ADJUSTMENT__C]                           DECIMAL (18, 2) NULL,
    [PS_ADJUSTMENT_COMMENTS__C]                  NTEXT           NULL,
    [PS_TOTAL__C]                                DECIMAL (18, 2) NULL,
    [LAST_TOUCH__C]                              DATETIME        NULL,
    [LAST_TOUCH_PUBLIC__C]                       DATETIME        NULL,
    [INSTALL_LOCATION__C]                        NVARCHAR (255)  NULL,
    [SUB_TYPE__C]                                NVARCHAR (255)  NULL,
    [SECONDARY_SUB_TYPE__C]                      NVARCHAR (255)  NULL,
    [SUNGARD_BRANDED_CUSTOMER__C]                NVARCHAR (255)  NULL,
    [GOOD_FAITH_ESTIMATE__C]                     DECIMAL (3)     NULL,
    [PARENT_ESTIMATED_COMPLETION_DATE__C]        DATETIME        NULL,
    [TOTAL_BILLABLE_HOURS__C]                    DECIMAL (8, 2)  NULL,
    [TOTAL_NON_BILLABLE_HOURS__C]                DECIMAL (8, 2)  NULL,
    [TOTAL_PS_ADJUSTMENTS__C]                    DECIMAL (18, 2) NULL,
    [TOTAL_PS_AMOUNT__C]                         DECIMAL (18, 2) NULL,
    [APPLICATION__C]                             NVARCHAR (255)  NULL,
    [BUSINESS_AREA__C]                           NVARCHAR (255)  NULL,
    [BUSINESS_SPONSOR__C]                        NVARCHAR (18)   NULL,
    [DUE_DATE__C]                                DATETIME        NULL,
    [ORIGINAL_ESTIMATED_COMPLETION_DATE__C]      DATETIME        NULL,
    [REQUESTER__C]                               NVARCHAR (18)   NULL,
    [EMAIL_TO_CASE_THREAD_ID__C]                 NVARCHAR (1300) NULL,
    [PO_NUMBER__C]                               NVARCHAR (255)  NULL,
    [SATISFACTION_WITH_SUPPORT__C]               NVARCHAR (255)  NULL,
    [CASE_AGE_HRS__C]                            DECIMAL (18, 2) NULL,
    [CASE_AGE_MINS__C]                           DECIMAL (18, 2) NULL,
    [AREA__C]                                    NVARCHAR (255)  NULL,
    [CATEGORY__C]                                NVARCHAR (255)  NULL,
    [PARTNER_LEVEL__C]                           NVARCHAR (1300) NULL,
    [DTS_LINK__C]                                NVARCHAR (1300) NULL,
    [DTS__C]                                     NVARCHAR (45)   NULL,
    [ISSUE__C]                                   NVARCHAR (255)  NULL,
    [OS__C]                                      NVARCHAR (255)  NULL,
    [OPTIONAL_SOFTWARE__C]                       NVARCHAR (255)  NULL,
    [PARENT_TICKET_FOR_REPORTS__C]               NVARCHAR (18)   NULL,
    [PRIORITY_ACCOUNT__C]                        NVARCHAR (1300) NULL,
    [RESOLUTION__C]                              NVARCHAR (255)  NULL,
    [SERVICE_PACK__C]                            NVARCHAR (50)   NULL,
    [ACCOUNT_SHIPPING_ADDRESS__C]                NVARCHAR (1300) NULL,
    [ACCOUNT_STATUS__C]                          NVARCHAR (1300) NULL,
    [NUMBER_OF_CDRS__C]                          DECIMAL (10)    NULL,
    [ACCOUNT_TYPE__C]                            NVARCHAR (1300) NULL,
    [ACCOUNT_VAULT__C]                           NVARCHAR (18)   NULL,
    [AFTER_HOURS__C]                             INT             NULL,
    [BILLABLE__C]                                INT             NULL,
    [BILLING_AMOUNT__C]                          DECIMAL (18, 2) NULL,
    [BRANDED_CUSTOMER__C]                        NVARCHAR (1300) NULL,
    [BUG_SYSTEM_LINK__C]                         NVARCHAR (255)  NULL,
    [CO_LOCATION__C]                             NVARCHAR (18)   NULL,
    [CONSULTANT__C]                              NVARCHAR (18)   NULL,
    [CUSTOMER_CONTACT_EMAIL__C]                  NVARCHAR (80)   NULL,
    [CUSTOMER_CONTACT_NAME__C]                   NVARCHAR (50)   NULL,
    [CUSTOMER_CONTACT_PHONE_NUMBER__C]           NVARCHAR (40)   NULL,
    [CUSTOMER_NAME__C]                           NVARCHAR (50)   NULL,
    [DAS_QSM__C]                                 NVARCHAR (18)   NULL,
    [DESIRED_TIME_TO_RESTORE__C]                 DATETIME        NULL,
    [END_DATETIME__C]                            DATETIME        NULL,
    [ESTIMATED_COMPLETION_DATE__C]               DATETIME        NULL,
    [FOLLOW_UP_DOCUMENTATION_REQUIRED__C]        INT             NULL,
    [HISTORICAL_TICKET_ID_NUMBER__C]             NVARCHAR (32)   NULL,
    [OPPORTUNITY__C]                             NVARCHAR (18)   NULL,
    [CLOSE_DATE_DAY_OF_WEEK__C]                  NVARCHAR (1300) NULL,
    [PARTNER_CONTACT__C]                         NVARCHAR (18)   NULL,
    [PRIMARY_OWNER__C]                           NVARCHAR (18)   NULL,
    [PRODUCT_CATEGORY__C]                        NVARCHAR (255)  NULL,
    [PRODUCT_LINE__C]                            NVARCHAR (255)  NULL,
    [PRODUCT_TICKET__C]                          NVARCHAR (32)   NULL,
    [PROJECT_END_DATE__C]                        DATETIME        NULL,
    [PROJECT_START_DATE__C]                      DATETIME        NULL,
    [SLXID__C]                                   NVARCHAR (18)   NULL,
    [SLX_OWNER__C]                               NVARCHAR (80)   NULL,
    [SOFTWARE_BUILD__C]                          NVARCHAR (128)  NULL,
    [START_DATETIME__C]                          DATETIME        NULL,
    [SUB_STATUS__C]                              NVARCHAR (255)  NULL,
    [TEMPORARY_FIX__C]                           INT             NULL,
    [TYPE_OF_SERVICE__C]                         NVARCHAR (1300) NULL,
    [VAULT_ACCOUNT_NAME__C]                      NVARCHAR (1300) NULL,
    [VAULT_COLOCATION__C]                        NVARCHAR (1300) NULL,
    [VAULT_CUSTOMER_SHORT_NAME__C]               NVARCHAR (1300) NULL,
    [VAULT_USER_NAME__C]                         NVARCHAR (1300) NULL,
    [VAULT_USER_PASSWORD__C]                     NVARCHAR (1300) NULL,
    [VAULT__C]                                   NVARCHAR (18)   NULL,
    [WEBCC_PASSWORD__C]                          NVARCHAR (1300) NULL,
    [WEBCC_URL__C]                               NVARCHAR (1300) NULL,
    [WEBCC_USERNAME__C]                          NVARCHAR (1300) NULL,
    [PO_DATE__C]                                 DATETIME        NULL,
    [CUSTOM__C]                                  INT             NULL,
    [INTERNATIONAL__C]                           INT             NULL,
    [SALES_ORDER_DATE__C]                        DATETIME        NULL,
    [ACTUAL_SHIP_DATE__C]                        DATETIME        NULL,
    [COMMIT_SHIP_DATE__C]                        DATETIME        NULL,
    [DELIVERY_DATE__C]                           DATETIME        NULL,
    [PROCUREMENT_PRODUCT__C]                     NVARCHAR (18)   NULL,
    [QUANTITY__C]                                DECIMAL (3)     NULL,
    [PO_AMOUNT__C]                               DECIMAL (18, 2) NULL,
    [CARRIER__C]                                 NVARCHAR (255)  NULL,
    [TRACKING_NUMBER__C]                         NVARCHAR (255)  NULL,
    [ACTUAL_HOURS__C]                            DECIMAL (12, 2) NULL,
    [DISTRIBUTOR_CUSTOMER_ID__C]                 NVARCHAR (100)  NULL,
    [DISTRIBUTOR_NAME__C]                        NVARCHAR (255)  NULL,
    [DISTRIBUTOR_ORDER_NO__C]                    NVARCHAR (18)   NULL,
    [DISTRIBUTOR_PARTNER_ID__C]                  NVARCHAR (100)  NULL,
    [DISTRIBUTOR_PARTNER__C]                     NVARCHAR (18)   NULL,
    [DISTRIBUTOR__C]                             NVARCHAR (18)   NULL,
    [EEP_ADMIN_EMAIL__C]                         NVARCHAR (80)   NULL,
    [EEP_ADMIN_NAME__C]                          NVARCHAR (255)  NULL,
    [ORDER_NO__C]                                NVARCHAR (255)  NULL,
    [ORDER_URL__C]                               NVARCHAR (255)  NULL,
    [COMMUNITY_DISCUSSION_URL__C]                NVARCHAR (255)  NULL,
    [PARTNER_TICKET_SHARING__C]                  INT             NULL,
    [PARTNER_ACCOUNT_SHARING__C]                 NVARCHAR (18)   NULL,
    [TICKET_OWNER_2__C]                          NVARCHAR (18)   NULL,
    [ERA_CONFIGURED__C]                          INT             NULL,
    [NUMBER_OF_AGENTS__C]                        DECIMAL (10)    NULL,
    [NUMBER_OF_ERAS__C]                          DECIMAL (10)    NULL,
    [ACCOUNT_DISTRICT__C]                        NVARCHAR (255)  NULL,
    [OTRK__C]                                    NVARCHAR (1300) NULL,
    [ACCOUNT_PARTNER_TYPE__C]                    NVARCHAR (255)  NULL,
    [ALLOCATED_ELITE_KICKSTART_FUNDS__C]         NVARCHAR (255)  NULL,
    [G2A4SF__CONNECTION_URL__C]                  NVARCHAR (255)  NULL,
    [ALLOCATED_PS_TRAINING_FUNDS__C]             NVARCHAR (255)  NULL,
    [G2A4SF__SESSION_CODE__C]                    NVARCHAR (50)   NULL,
    [CREATED_GP_ACCOUNT__C]                      INT             NULL,
    [CREATED_GP_SALES_ORDER__C]                  NVARCHAR (255)  NULL,
    [DELIVERED_BILLING_INSTRUCTIONS__C]          NVARCHAR (255)  NULL,
    [REQUIREMENTS_DOCUMENT__C]                   NVARCHAR (255)  NULL,
    [CUSTOMER_PARTNER_LEVEL__C]                  NVARCHAR (1300) NULL,
    [PARTNER_ACCOUNT_UPDATED__C]                 INT             NULL,
    [PARTNER_CONTRACT_EXECUTED__C]               INT             NULL,
    [PARTNER_INVOICED__C]                        NVARCHAR (255)  NULL,
    [TECS_PO_ATTACHED_TO_ACCOUNT__C]             NVARCHAR (255)  NULL,
    [PARTNER_PORTAL_OVERVIEW__C]                 NVARCHAR (255)  NULL,
    [PORTAL_ACCESS_PROVISIONED__C]               NVARCHAR (255)  NULL,
    [PROJECT_MANAGEMENT__C]                      DECIMAL (2)     NULL,
    [EXECUTION__C]                               DECIMAL (2)     NULL,
    [VERIFIED_PARTNER_ONBOARDING_INFORMATION__C] INT             NULL,
    [REVIEW_ON__C]                               DATETIME        NULL,
    [TICKET_OWNER_ROLE__C]                       NVARCHAR (1300) NULL,
    [BOOKING__C]                                 NVARCHAR (18)   NULL,
    [FRN__C]                                     NVARCHAR (18)   NULL,
    [ERA_VAULT_RECORD_CREATED__C]                INT             NULL,
    [ROOT_CAUSE_SUBCATEGORY__C]                  NVARCHAR (255)  NULL,
    [CONTRACT__C]                                NVARCHAR (18)   NULL,
    [SEVERITY__C]                                NVARCHAR (255)  NULL,
    [GB_LOST_ORIGINAL__C]                        DECIMAL (8, 2)  NULL,
    [GB_LOST_POOLSIZE__C]                        DECIMAL (8, 2)  NULL,
    [LAST_TOUCH_BY_OWNER__C]                     DATETIME        NULL,
    [HIVE_INSTALLED__C]                          INT             NULL,
    [DATE_OF_DISCOVERY__C]                       DATETIME        NULL,
    [DATE_OF_DATA_LOSS_EVENT__C]                 DATETIME        NULL,
    [DATE_OF_RESOLUTION__C]                      DATETIME        NULL,
    [ROOT_CAUSE_OF_LOSS__C]                      NVARCHAR (255)  NULL,
    [REMEDIATION_PLAN__C]                        NTEXT           NULL,
    [DAS_QSM_STATUS__C]                          NVARCHAR (1300) NULL,
    [NO_OF_TASKS__C]                             DECIMAL (6)     NULL,
    [NO_OF_SAFESETS__C]                          DECIMAL (6)     NULL,
    [RCA_DOCUMENT__C]                            NVARCHAR (255)  NULL,
    [ESCALATIONS_TYPE__C]                        NVARCHAR (255)  NULL,
    [JIRA_ISSUE_URL__C]                          NVARCHAR (255)  NULL,
    [EXEMPTION_REASON__C]                        NVARCHAR (1000) NULL,
    [ROOT_CAUSE__C]                              NVARCHAR (255)  NULL,
    [ROOT_CAUSE_DESCRIPTION__C]                  NVARCHAR (255)  NULL,
    [RESOLUTION_DESCRIPTION__C]                  NTEXT           NULL,
    [VAULT_EXTERNAL_FQDN__C]                     NVARCHAR (1300) NULL,
    [SLA_IMAGE__C]                               NVARCHAR (1300) NULL,
    [SLA_STATUS__C]                              NVARCHAR (1300) NULL,
    [SLA_TIME_ELAPSED__C]                        DECIMAL (18, 2) NULL,
    [SLA_TIME_REMAINING__C]                      DECIMAL (18, 2) NULL,
    [COMPANY_INITIATIVE__C]                      NVARCHAR (255)  NULL,
    [ACCOUNT_PARTNER_SUB_TYPE__C]                NTEXT           NULL,
    [AZURE_EVAULT__C]                            INT             NULL,
    [AZURE_AEA__C]                               DECIMAL (4)     NULL,
    [AZURE_AEU__C]                               DECIMAL (4)     NULL,
    [AZURE_ANE__C]                               DECIMAL (4)     NULL,
    [AZURE_ASA__C]                               DECIMAL (4)     NULL,
    [AZURE_AWE__C]                               DECIMAL (4)     NULL,
    [AZURE_AWU__C]                               DECIMAL (4)     NULL,
    [AZURE_TOTAL_TB__C]                          DECIMAL (4)     NULL,
    [TICKET_USER_ROLE__C]                        NVARCHAR (255)  NULL,
    [LAST_COMMENT__C]                            NVARCHAR (255)  NULL,
    [LAST_COMMENT_DATE__C]                       DATETIME        NULL,
    [MONITORING_TYPE__C]                         NVARCHAR (255)  NULL,
    [DISTRIBUTOR_CONTACT__C]                     NVARCHAR (18)   NULL,
    [FULFILLMENT_TICKET__C]                      INT             NULL,
    [LINE_ID__C]                                 DECIMAL (2)     NULL,
    [MEMO__C]                                    NTEXT           NULL,
    [PRODUCT2__C]                                NVARCHAR (18)   NULL,
    [PRODUCT_DESCRIPTION__C]                     NVARCHAR (255)  NULL,
    [RELAYWARE_ID__C]                            DECIMAL (18)    NULL,
    [RESELLER_ACCOUNT__C]                        NVARCHAR (18)   NULL,
    [RESELLER_CONTACT__C]                        NVARCHAR (18)   NULL,
    [TRANSACTION__C]                             NVARCHAR (18)   NULL,
    [AUTOMATION_STATUS__C]                       NVARCHAR (255)  NULL,
    [LICENSES__C]                                NTEXT           NULL,
    [HIDDEN_ADMIN_TEXT_FIELD__C]                 NVARCHAR (255)  NULL,
    [NETSUITE_CUSTOMER_NUMBER__C]                NVARCHAR (1300) NULL,
    [SUPPORTED_PRODUCT__C]                       NVARCHAR (255)  NULL,
    [PROVISIONING_INSTRUCTIONS__C]               NVARCHAR (1000) NULL,
    [PRIORITY_ORDER__C]                          DECIMAL (3)     NULL,
    [INSTALLATION_HEALTH__C]                     NVARCHAR (255)  NULL,
    [INSTALLATION_STATUS__C]                     NVARCHAR (255)  NULL,
    [INSTALLATION_REASON__C]                     NVARCHAR (255)  NULL,
    [CATEGORY_TYPE__C]                           NVARCHAR (255)  NULL,
    [DIVISION__C]                                NVARCHAR (255)  NULL,
    [CRITICAL_WATCH_LIST__C]                     INT             NULL,
    [REOCCURRENCE_OF_PAST_ISSUE__C]              INT             NULL,
    [RESELLER_ACCOUNT_MANAGER__C]                NVARCHAR (1300) NULL,
    [BILLING_ISSUE_ROOT_CAUSE__C]                NVARCHAR (255)  NULL,
    [IDENTIFIED_BY__C]                           NVARCHAR (255)  NULL,
    [INVOICE__C]                                 NVARCHAR (18)   NULL,
    [INVOICE_AMOUNT__C]                          DECIMAL (18, 8) NULL,
    [PROBLEM__C]                                 NTEXT           NULL,
    [RESOLUTION_STORY__C]                        NTEXT           NULL,
    [ROOT_CAUSE_STORY__C]                        NTEXT           NULL,
    [ASSET_COMMENTS__C]                          NVARCHAR (255)  NULL,
    [COMPONENT__C]                               NTEXT           NULL,
    [CREATED_DATE_DAY_OF_WEEK__C]                NVARCHAR (1300) NULL,
    [ESCALATION_REASON__C]                       NVARCHAR (255)  NULL,
    [ESCALATION_SOURCE__C]                       NVARCHAR (255)  NULL,
    [ESCALATION_SUMMARY__C]                      NTEXT           NULL,
    [FIX_TRAJECTORY__C]                          NVARCHAR (255)  NULL,
    [JIRA_ATTACHMENT_LINKS__C]                   NTEXT           NULL,
    [JIRA_DESCRIPTION__C]                        NTEXT           NULL,
    [JIRA_PRIORITY__C]                           NVARCHAR (255)  NULL,
    [JIRA_STATUS__C]                             NVARCHAR (255)  NULL,
    [JIRA_SUMMARY__C]                            NVARCHAR (255)  NULL,
    [MINUTES_TO_ASSIGN_FROM_QUEUE__C]            DECIMAL (18, 2) NULL,
    [MODEL__C]                                   NVARCHAR (255)  NULL,
    [NEXT_STEPS__C]                              NVARCHAR (255)  NULL,
    [SUB_COMPONENT__C]                           NVARCHAR (255)  NULL,
    [SYSTEM_STATE__C]                            NVARCHAR (255)  NULL,
    [SYSTEM_TYPE__C]                             NVARCHAR (255)  NULL,
    [X_JIRA_KEY__C]                              NVARCHAR (255)  NULL,
    [X_SHIPPING_INFORMATION__C]                  NTEXT           NULL,
    [X_STEPS_TO_REPRODUCE__C]                    NTEXT           NULL,
    [SUNGARD_TICKET_ID__C]                       NVARCHAR (32)   NULL,
    [EXTERNAL_URL__C]                            NVARCHAR (255)  NULL,
    [URGENCY__C]                                 NVARCHAR (255)  NULL,
    [EFFORT__C]                                  NVARCHAR (255)  NULL,
    [DEVELOPMENT_REQUIRED__C]                    INT             NULL,
    [BILLABLE_CASE_TIME_TRACKER_TOTAL__C]        DECIMAL (18, 2) NULL,
    [NON_BILLABLE_CASE_TIME_TRACKER_TOTAL__C]    DECIMAL (18, 2) NULL,
    [CASE_TIME_TRACKER_TOTAL__C]                 DECIMAL (18, 2) NULL,
    [IRM_INFLUENCED__C]                          INT             NULL,
    [TRIAL_ID__C]                                NVARCHAR (40)   NULL,
    [COST_SAVINGS__C]                            NVARCHAR (255)  NULL,
    [REVENUE_GENERATION__C]                      NVARCHAR (255)  NULL,
    [CUSTOMER_EXPERIENCE__C]                     NVARCHAR (255)  NULL,
    [REQUEST_TYPE__C]                            NVARCHAR (255)  NULL,
    [UNIQUE_COUNT__C]                            DECIMAL (18)    NULL,
    [PLATFORM__C]                                NVARCHAR (255)  NULL,
    [PLUGIN_TOOL__C]                             NVARCHAR (255)  NULL,
    [PRODUCT_SUB__C]                             NVARCHAR (255)  NULL,
    [SUPPORT_TYPE__C]                            NVARCHAR (255)  NULL,
    [PERCENT_COMPLETED__C]                       NVARCHAR (255)  NULL,
    [CONFIDENCE_LEVEL__C]                        NVARCHAR (255)  NULL,
    [INCIDENT_NOTES__C]                          NVARCHAR (255)  NULL,
    [MACHINE_NAME__C]                            NVARCHAR (128)  NULL,
    [TASK_NAME__C]                               NVARCHAR (128)  NULL,
    [ORIGINAL_CLOSED_DATE_TIME__C]               DATETIME        NULL,
    [SUBSTATUS__C]                               NVARCHAR (255)  NULL,
    [CLOSE_CASE_TOKEN__C]                        NVARCHAR (255)  NULL,
    [SUPPORT_QUEUE__C]                           NVARCHAR (25)   NULL,
    [EXTERNAL_FUL2_ID__C]                        NVARCHAR (18)   NULL,
    [OUT_OF_OFFICE_OVERRIDE__C]                  INT             NULL,
    [ACCOUNT_ID__C]                              NVARCHAR (1300) NULL,
    [ACCOUNT_SALES_REGION__C]                    NVARCHAR (1300) NULL,
    [ACCOUNT_VAULT_STATUS__C]                    NVARCHAR (1300) NULL,
    [CLOSED_BY__C]                               NVARCHAR (128)  NULL,
    [FORENSICS_LOCATION__C]                      NVARCHAR (255)  NULL,
    [SCHEDULED_CALLBACK_DATE_TIME__C]            DATETIME        NULL,
    [TOTAL_CONTRACTED_STORAGE_GB__C]             DECIMAL (18, 2) NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191338901EV_SF_CASE_ID]
    ON [dbo].[EV_SF_CASE]([ID] ASC);

