CREATE TABLE [dbo].[EV_SF_ACCOUNTHISTORY] (
    [ID]          NVARCHAR (18)  NULL,
    [ISDELETED]   INT            NULL,
    [ACCOUNTID]   NVARCHAR (18)  NULL,
    [CREATEDBYID] NVARCHAR (18)  NULL,
    [CREATEDDATE] DATETIME       NULL,
    [FIELD]       NVARCHAR (255) NULL,
    [OLDVALUE]    NVARCHAR (255) NULL,
    [NEWVALUE]    NVARCHAR (255) NULL
);


GO
CREATE NONCLUSTERED INDEX [x1609191314589EV_SF2_ACCOUNTHI]
    ON [dbo].[EV_SF_ACCOUNTHISTORY]([ID] ASC);

