CREATE TABLE [import].[SM_Contracts] (
    [Contract_ID]                  VARCHAR (999)   NULL,
    [Contract_Line_ID]             VARCHAR (999)   NULL,
    [Original_NS_CL_ID]            VARCHAR (999)   NULL,
    [Contract_Name]                NVARCHAR (999)  NULL,
    [Contract_Line_Name]           NVARCHAR (999)  NULL,
    [Contract_Line_Status]         NVARCHAR (999)  NULL,
    [Customer]                     NVARCHAR (256)  NULL,
    [Reseller]                     NVARCHAR (256)  NULL,
    [End_User]                     NVARCHAR (256)  NULL,
    [Customer_End_User]            NVARCHAR (256)  NULL,
    [Customer_ID]                  BIGINT          NULL,
    [Reseller_ID]                  BIGINT          NULL,
    [End_User_ID]                  BIGINT          NULL,
    [Customer_End_User_ID]         BIGINT          NULL,
    [Customer_SFDC_ID]             NVARCHAR (100)  NULL,
    [Reseller_SFDC_ID]             NVARCHAR (100)  NULL,
    [End_User_SFDC_ID]             NVARCHAR (100)  NULL,
    [Customer_End_User_SFDC_ID]    NVARCHAR (100)  NULL,
    [Customer_NS_Number]           NVARCHAR (99)   NULL,
    [Reseller_NS_Number]           NVARCHAR (99)   NULL,
    [End_User_NS_Number]           NVARCHAR (99)   NULL,
    [Customer_End_User_NS_Number]  NVARCHAR (99)   NULL,
    [Direct_Indirect_Distributor]  VARCHAR (50)    NOT NULL,
    [Initial_Contract_Date]        DATE            NULL,
    [Customer_Account_Type]        NVARCHAR (99)   NULL,
    [Order_Line_Transaction_Type]  NVARCHAR (999)  NULL,
    [Sales_Product_Group]          NVARCHAR (999)  NULL,
    [Sales_Product_Type]           NVARCHAR (999)  NULL,
    [Pricing_Group]                NVARCHAR (60)   NULL,
    [Product_Type]                 NVARCHAR (999)  NULL,
    [Booking_Category]             NVARCHAR (999)  NULL,
    [Booking_Product_Group]        NVARCHAR (999)  NULL,
    [Contract_Line_Product_Type]   NVARCHAR (100)  NULL,
    [Item]                         NVARCHAR (4000) NULL,
    [Contract_Line_SFDC_ID]        NVARCHAR (99)   NULL,
    [SKU]                          NVARCHAR (4000) NULL,
    [Quantity]                     FLOAT (53)      NULL,
    [Included_Usage_GB]            BIGINT          NULL,
    [Calculated_Included_Usage_GB] BIGINT          NULL,
    [Contracted_Unit_Rate]         FLOAT (53)      NULL,
    [Contracted_Unit_Rate_USD]     NUMERIC (15, 2) NULL,
    [Contracted_Amount]            FLOAT (53)      NULL,
    [Contracted_Amount_USD]        NUMERIC (15, 2) NULL,
    [Monthly_Value]                FLOAT (53)      NULL,
    [Quarterly_Value]              FLOAT (53)      NULL,
    [Semiannual_Value]             FLOAT (53)      NULL,
    [Annual_Value]                 FLOAT (53)      NULL,
    [Currency]                     NVARCHAR (4)    NULL,
    [Superseded_By_ID]             VARCHAR (999)   NULL,
    [Supersedes_ID]                VARCHAR (999)   NULL,
    [Start_Date]                   DATETIME2 (7)   NULL,
    [End_Date]                     DATETIME2 (7)   NULL,
    [Renew_Date]                   DATETIME2 (7)   NULL,
    [Term_Month]                   FLOAT (53)      NULL,
    [End_of_Term_Action]           NVARCHAR (999)  NULL
);

