CREATE TABLE [dbo].[NSCARB_CURRENCYRATES] (
    [ANCHOR_CURRENCY_ID]       FLOAT (53)    NULL,
    [BASE_CURRENCY_ID]         FLOAT (53)    NULL,
    [CURRENCYRATE_ID]          FLOAT (53)    NULL,
    [CURRENCYRATE_PROVIDER_ID] NVARCHAR (8)  NULL,
    [CURRENCY_ID]              FLOAT (53)    NULL,
    [DATE_EFFECTIVE]           DATETIME2 (7) NULL,
    [DATE_LAST_MODIFIED]       DATETIME2 (7) NULL,
    [EXCHANGE_RATE]            FLOAT (53)    NULL,
    [IS_ANCHOR_ONLY]           NVARCHAR (3)  NULL,
    [UPDATE_METHOD_ID]         NVARCHAR (8)  NULL
);

