CREATE TABLE [dbo].[NSCARB_SALES_TEAM_ROLE] (
    [DATE_CREATED]          DATETIME2 (7)  NULL,
    [IS_RECORD_INACTIVE]    NVARCHAR (250) NULL,
    [LAST_MODIFIED_DATE]    DATETIME2 (7)  NULL,
    [LIST_ID]               FLOAT (53)     NULL,
    [LIST_ITEM_NAME]        NVARCHAR (250) NULL,
    [SALES_TEAM_ROLE_EXTID] FLOAT (53)     NULL
);

