CREATE TABLE [dbo].[NSCARB_TRANSACTION_LINKS] (
    [AMOUNT_FOREIGN_LINKED]        FLOAT (53)     NULL,
    [AMOUNT_LINKED]                FLOAT (53)     NULL,
    [APPLIED_DATE_POSTED]          DATETIME2 (7)  NULL,
    [APPLIED_TRANSACTION_ID]       FLOAT (53)     NULL,
    [APPLIED_TRANSACTION_LINE_ID]  FLOAT (53)     NULL,
    [DATE_LAST_MODIFIED]           DATETIME2 (7)  NULL,
    [DISCOUNT]                     NVARCHAR (3)   NULL,
    [INVENTORY_NUMBER]             NVARCHAR (100) NULL,
    [LINK_TYPE]                    NVARCHAR (128) NULL,
    [ORIGINAL_DATE_POSTED]         DATETIME2 (7)  NULL,
    [ORIGINAL_TRANSACTION_ID]      FLOAT (53)     NULL,
    [ORIGINAL_TRANSACTION_LINE_ID] FLOAT (53)     NULL,
    [QUANTITY_LINKED]              FLOAT (53)     NULL
);

