CREATE TABLE [dbo].[NSCARB_REVENUE_PLANS] (
    [ACCOUNTING_PERIOD_ID] FLOAT (53)     NULL,
    [COMMENTS]             NVARCHAR (500) NULL,
    [DATE_CREATED]         DATETIME2 (7)  NULL,
    [DATE_LAST_MODIFIED]   DATETIME2 (7)  NULL,
    [END_DATE]             DATETIME2 (7)  NULL,
    [IS_HOLD_REV_REC]      NVARCHAR (3)   NULL,
    [PLAN_ID]              FLOAT (53)     NULL,
    [PLAN_NUMBER]          NVARCHAR (99)  NULL,
    [REFORECAST_METHOD]    NVARCHAR (150) NULL,
    [REVENUE_ELEMENT_ID]   FLOAT (53)     NULL,
    [REVENUE_PLAN_TYPE]    NVARCHAR (50)  NULL,
    [REV_REC_RULE_ID]      FLOAT (53)     NULL,
    [START_DATE]           DATETIME2 (7)  NULL
);

