CREATE TABLE [dbo].[NSCARB_CONSOLIDATED_EXCHANGE_RATES] (
    [ACCOUNTING_PERIOD_ID]          FLOAT (53) NULL,
    [AVERAGE_BUDGET_RATE]           FLOAT (53) NULL,
    [AVERAGE_RATE]                  FLOAT (53) NULL,
    [CONSOLIDATED_EXCHANGE_RATE_ID] FLOAT (53) NULL,
    [CURRENT_BUDGET_RATE]           FLOAT (53) NULL,
    [CURRENT_RATE]                  FLOAT (53) NULL,
    [FROM_SUBSIDIARY_ID]            FLOAT (53) NULL,
    [HISTORICAL_BUDGET_RATE]        FLOAT (53) NULL,
    [HISTORICAL_RATE]               FLOAT (53) NULL,
    [TO_SUBSIDIARY_ID]              FLOAT (53) NULL
);

